### PR TITLE
IDEMPIERE-5168 column AD_AuthorizationAccount.AccessToken is short on some case

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
https://idempiere.atlassian.net/browse/IDEMPIERE-5168

- Allow reference Text with length 0 to be managed as CLOB/TEXT
- Increase AD_ChangeLog.OldValue/NewValue to 4000 to allow saving more information about changing long texts
- Change AD_AuthorizationAccount.AccessToken to CLOB/TEXT
- Change some important actual columns defined as Text Long, to Text with length 0 (this allows changelog, better 2Pack, encryption)

### CODE REVIEW

**Comment by hieplq** [comment]
it look ok but "Access Token" field on gird mode become not secure anymore

image

**Comment by CarlosRuiz-globalqss** [comment]
> it look ok but "Access Token" field on gird mode become not secure anymore
> 

Hi @hieplq - sorry, don't understand what you are reporting.

The Encryption defined in Column just happen on database, the UI still shows the values to the user.

The Encryption defined in Field just happen on UI, masking the value with ********

**Comment by hieplq** [comment]
> > it look ok but "Access Token" field on gird mode become not secure anymore
> 
> Hi @hieplq - sorry, don't understand what you are reporting.
> 
> The Encryption defined in Column just happen on database, the UI still shows the values to the user.
> 
> The Encryption defined in Field just happen on UI, masking the value with ********

"Access Token" is same as "Refresh Token" both is encryption field also encryption column

i found logic make that issue

by bellow logic then text long and text secure only on gird model

image

**Comment by CarlosRuiz-globalqss** [comment]
> "Access Token" is same as "Refresh Token" both is encryption field also encryption column
> i found logic make that issue
> by bellow logic then text long and text secure only on gird model

Thanks @hieplq - I committed a fix for that

**Review by hieplq — APPROVED** [review]

**Pull request merged**
