### PR TITLE
IDEMPIERE-5943 Implement table partitioning support

### PR DESCRIPTION
**Pull request by hengsin**
- Fix issues with view and functional index

https://idempiere.atlassian.net/browse/IDEMPIERE-5943

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [x] I have tested the direct scenario that my code is solving
- [x] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

### CODE REVIEW

**Comment by norbertbede** [comment]
@PeterTakacs300 pls test it you will be available. Thanks @hengsin

**Comment by PeterTakacs300** [comment]
Hi @hengsin the functional index issue works now, but the view issue is still there.

If I partition the C_Order table, RV_OrderDetail is still modified `FROM adempiere.c_order o` -> `FROM adempiere.c_order_default_partition o`

**Comment by hengsin** [comment]
hi @PeterTakacs300 ,
- I can't re-produce the 2 issue you posted above.
- Note that the cascade dropping of constraint is a must for PostgreSQL due to the PostgreSQL table partitioning limitation for primary key.

**Comment by norbertbede** [comment]
thanks @PeterTakacs300 and @hengsin  for testing. Probably we did something wrong, i would like kindly ask @CarlosRuiz-globalqss to make a small test. thanks

we tested the try the next tables (accidentally no information list or range - but previously i discovered this at range)
- m_transaction
- c_order
- c_invoice

**Comment by hengsin** [comment]
hi @PeterTakacs300 , please double check you have merge correctly the changes. My query result below after partitioning of c_order table clearly show that the rv_orderdetail view is not retrieving from c_order_default_partition.

'''
idempiere=# select count(*) from c_order;
count 
-------
     8
(1 row)

idempiere=# select count(*) from c_order_default_partition ;
count 
-------
     0
(1 row)

idempiere=# select count(*) from rv_orderdetail;
count 
-------
    27
(1 row)
'''

**Comment by PeterTakacs300** [comment]
Hi @hengsin, I've double checked the code and my database too, but couldn't find any issue/change that could cause this problem

I've tested with the following:
- branch pr/2203 (I have all the code you committed, branch from master - v12)
- run all migration scripts until this point (I have a clean iDempiere database)
- partition C_Order - mode: list
- `select count(*) from rv_orderdetail;` returns 0 lines
- I've recorded a video below, another test with C_Invoice and RV_C_Invoice, mode: Range - 1 month

https://github.com/idempiere/idempiere/assets/93127072/ebbdf6a2-8efc-4a1b-9372-8257a7338bc3

After this, I've merged this PR to our Cloudempiere code and tested on our DB as well, with the same result (row count 0).
Cannot think of anything else, maybe is a good idea that third person tests is too, as Norbert wrote above.

**Comment by alanlesc1** [comment]
Hi @PeterTakacs300, I made a test and I got the same results as @hengsin. I installed a clean master (today code) and followed the steps in your video. Result: RV_C_invoice is getting data from C_Invoice. Tested also with C_Order and I got the same counts from here: https://github.com/idempiere/idempiere/pull/2203#issuecomment-1913542533

Maybe some pg version issue? Mine is 14.5

**Comment by norbertbede** [comment]
tomorrow we will repat a new clean test, again. on v16.1 latest PG. and latest iD 12. 
i would kindly ask @CarlosRuiz-globalqss for a quick test too. 
nb

**Comment by hengsin** [comment]
For the record, mine is PostgreSQL 15.4

**Comment by norbertbede** [comment]
wondering do we need to test 15.4 or others test with 16.1. would be happy to close this issue week if possible.

**Comment by hengsin** [comment]
tested with pg 16.1 just now and indeed the fix is not working with 16.1

**Comment by hengsin** [comment]
hi @norbertbede , I've push the fix for PostgreSQL 16.1 (tested with 15.4 too), please re-test.

**Comment by hengsin** [comment]
Btw, the incompatible SQL is duplicated from the `altercolumn(name, name, name,  character varying, character varying, name)` function so that's likely broken for PostgreSQL 16 too.

**Comment by PeterTakacs300** [comment]
Hi @hengsin thanks for the quick fix, now it work well for me too, tested with PostgreSQL 16.0

**Comment by norbertbede** [comment]
great work, thanks for all

**Comment by CarlosRuiz-globalqss** [comment]
> Btw, the incompatible SQL is duplicated from the `altercolumn(name, name, name, character varying, character varying, name)` function so that's likely broken for PostgreSQL 16 too.

@hengsin - test.idempiere.org is set on postgresql 16, so it can be used to check if this is broken

**Pull request merged**
