### PR TITLE
IDEMPIERE-5515 Processes Generate "Unknown Parameter: ..." logs

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
https://idempiere.atlassian.net/browse/IDEMPIERE-5515

## Checklist:
- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by nmicoud** [comment]
Hi,
I'm currently installing v10 environment, but I'm facing a blocker issue since the artifact org.zkoss.theme:breeze:jar:9.6.3 is not downloadable :(
I'll review this ticket asap

**Comment by nmicoud** [comment]
Hi @CarlosRuiz-globalqss ,

I've tested it and I think I don't understand what you wanted to achieve as I was not able to generate a 'Custom' parameter log.

Here's the tests I've conducted :
I've added AD_User_ID on AllocationAuto and executed the process with no value.
Nothing appears in the log (as validateUnknownParameter won't be called). This parameter was "hidden" - not sure if that needs to be fixed.

Then, I filled it with a user and execute it, and I saw in log:
14:19:54.850===========> MProcessPara.validateUnknownParameter: Process C_Allocation_Auto - Unknown Parameter: AD_User_ID=WebService

Then I execute the CacheReset process and re-ran AllocationAuto ; log was empty.

So not sure how that should be tested :-/

**Comment by CarlosRuiz-globalqss** [comment]
Hi @nmicoud - thanks for testing

What is your log level?  To test this you need INFO level (and maybe test in master because log works strangely before IDEMPIERE-5548)

The patch is intended to generate a level INFO log when the parameter is found active in the dictionary (ad_process_para) - I think this is your case.

The second test - to generate a SEVERE log when the parameter is not found in ad_process_para - cannot be replicated within iDempiere, but for example webservices passing parameters can easily pass a wrong parameter name and in this case the error must appear.

Regards,

Carlos Ruiz

**Comment by nmicoud** [comment]
Hi @CarlosRuiz-globalqss,

Thanks for clarification.

I've made some tests and here's what I found.
Log level was set to FINE.

I've run RunStorageDetail as a WS (as is set up in GW)

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:_0="http://idempiere.org/ADInterface/1_0">
   <soapenv:Header/>
   <soapenv:Body>
      <_0:runProcess>
         <_0:ModelRunProcessRequest>
         <_0:ModelRunProcess AD_Process_ID="236">
               <_0:serviceType>RunStorageDetail</_0:serviceType>
               <_0:ParamValues>
                 <_0:field column="AD_User_ID"><_0:val>1002321</_0:val></_0:field>
			  <_0:field column="Language"><_0:val>bg-BG</_0:val></_0:field>
			  <_0:field column="IsForceRenew"><_0:val>Y</_0:val></_0:field> 
               </_0:ParamValues>
            </_0:ModelRunProcess>
		<_0:ADLoginRequest>
			<_0:user>WebService</_0:user>
			<_0:pass>WebService</_0:pass>
			<_0:lang>en_US</_0:lang>
			<_0:ClientID>11</_0:ClientID>
			<_0:RoleID>50004</_0:RoleID>
			<_0:OrgID>0</_0:OrgID>
			<_0:WarehouseID>0</_0:WarehouseID>
			<_0:stage>0</_0:stage>
		</_0:ADLoginRequest>
         </_0:ModelRunProcessRequest>
      </_0:runProcess>
   </soapenv:Body>
</soapenv:Envelope>

Nothing appears in log whereas the 3 parameters are not set in AD.
Then I realize there was no java class... so it can be considered as 'normal'

So I've set up CacheReset to be called from WS

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:_0="http://idempiere.org/ADInterface/1_0">
   <soapenv:Header/>
   <soapenv:Body>
      <_0:runProcess>
         <_0:ModelRunProcessRequest>
         <_0:ModelRunProcess AD_Process_ID="205">
               <_0:serviceType>RunCacheReset</_0:serviceType>
               <_0:ParamValues>
                 <_0:field column="AD_User_ID"><_0:val>1002321</_0:val></_0:field>
			  <_0:field column="Language"><_0:val>bg-BG</_0:val></_0:field>
			  <_0:field column="IsForceRenew"><_0:val>Y</_0:val></_0:field> 
               </_0:ParamValues>
            </_0:ModelRunProcess>
		<_0:ADLoginRequest>
			<_0:user>WebService</_0:user>
			<_0:pass>WebService</_0:pass>
			<_0:lang>en_US</_0:lang>
			<_0:ClientID>11</_0:ClientID>
			<_0:RoleID>50004</_0:RoleID>
			<_0:OrgID>0</_0:OrgID>
			<_0:WarehouseID>0</_0:WarehouseID>
			<_0:stage>0</_0:stage>
		</_0:ADLoginRequest>
         </_0:ModelRunProcessRequest>
      </_0:runProcess>
   </soapenv:Body>
</soapenv:Envelope>

And here again, nothing appears in log. Because the prepareIt method is empty.


So, I set AllocationAuto


<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:_0="http://idempiere.org/ADInterface/1_0">
   <soapenv:Header/>
   <soapenv:Body>
      <_0:runProcess>
         <_0:ModelRunProcessRequest>
         <_0:ModelRunProcess AD_Process_ID="302">
               <_0:serviceType>RunAutoAllocation</_0:serviceType>
               <_0:ParamValues>
				<_0:field column="APAR"><_0:val>AP</_0:val></_0:field>
                 <_0:field column="AD_User_ID"><_0:val>1002321</_0:val></_0:field>
			  <_0:field column="Language"><_0:val>bg-BG</_0:val></_0:field>
			  <_0:field column="IsForceRenew"><_0:val>Y</_0:val></_0:field> 
               </_0:ParamValues>
            </_0:ModelRunProcess>
		<_0:ADLoginRequest>
			<_0:user>WebService</_0:user>
			<_0:pass>WebService</_0:pass>
			<_0:lang>en_US</_0:lang>
			<_0:ClientID>11</_0:ClientID>
			<_0:RoleID>50004</_0:RoleID>
			<_0:OrgID>0</_0:OrgID>
			<_0:WarehouseID>0</_0:WarehouseID>
			<_0:stage>0</_0:stage>
		</_0:ADLoginRequest>
         </_0:ModelRunProcessRequest>
      </_0:runProcess>
   </soapenv:Body>
</soapenv:Envelope>

But I only got the AD_User_ID parameter in log:

07:53:21.765 MProcess.startClass: org.compiere.process.AllocationAuto [634]
current param name : APAR
current param name : AllocateOldest
current param name : AD_User_ID
07:53:21.766 MProcessPara.validateUnknownParameter: Process C_Allocation_Auto - Custom Parameter: AD_User_ID=User/Contact [634]

Other were ignored ; did I miss something ?

At the end, I think those cases can be left as it (as it's not the scope of the ticket).
But maybe it's good to have that in mind for another ticket? Not sure if it's necessary to handle them?

**Comment by CarlosRuiz-globalqss** [comment]
> 
> Other were ignored ; did I miss something ?
> 
> At the end, I think those cases can be left as it (as it's not the scope of the ticket). But maybe it's good to have that in mind for another ticket? Not sure if it's necessary to handle them?

Thanks @nmicoud for the tests.

Probably SOAP webservices are filtering out any parameter that is not on the dictionary, haven't tested that scenario.  I barely use SOAP.

My test was directly in eclipse breakpoint in prepare method and changing the parameter name.

**Comment by CarlosRuiz-globalqss** [comment]
> And here again, nothing appears in log. Because the prepareIt method is empty.

Ah yes - by the way I noticed there are a lot of methods with prepareIt empty, and others without code to check parameters, I left those methods untouched.

A few methods have parameter assignment but not validation, I added the validation for those at the end.

**Pull request merged**
