### PR TITLE
idempiere-4535 support local target platform

### PR DESCRIPTION
**Pull request by hieplq**
how it implement
1. use groovy maven plus to run scrip (https://groovy.github.io/GMavenPlus/)
   1.1 copy generate repository ([idempiere]/org.idempiere.p2/target/repository) to local repository (-DrepositoryPath)
   1.2 use template ([idempiere]/org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatformlocal.template.tpd) to create org.idempiere.p2.targetplatformlocal.tpd with replace placeholder of local repository path

2. use targetplatform-dsl to generate local target file from org.idempiere.p2.targetplatformlocal.tpd (https://github.com/eclipse-cbi/targetplatform-dsl)
   2.1 it help to pickup version of bundle from local repository to target platform file
   2.2 filter out idempiere bundle

how to use
1. first time setup workspace run "mvn verify" as before
   1.1 groovy generate local repository at "[idempiere]/localRepository"
   1.2 targetplatform-dsl generate local target file at "idempiere/org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatformlocal.target"
2. when setup eclipse do active local target platform
3. next build to use local target run "mvn verify -Dmode=local"

more customize
1. to share a local repository for multi workspace do as bellow
  1.1 use repositoryPath to define local repository outside [idempiere], first time use this command to generate local repository "mvn verify -DrepositoryPath=/home/locall/repository"
  1.2 when setup other workspace, just re-use by use command "mvn verify -DrepositoryPath=/home/locall/repository -Dmode=local"
  1.3 when community update target platform then use updateRepository to re-generate local repository by run "mvn verify -DrepositoryPath=/home/locall/repository -DupdateRepository=true"

### CODE REVIEW

**Comment by hengsin** [comment]
Try it out today and it fail with the following error:
[ERROR]   No installable unit with ID 'org.apache.commons.math3' can be found in 'file://home/hengsin/workspace/idempiere-master/idempiere/localRepository'

[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-eclipserun-plugin:2.1.0:eclipse-run (generate local target platform) on project org.idempiere.p2: Error while executing platform: Error while executing platform (return code: 255) -> [Help 1]

**Comment by hieplq** [comment]
@hengsin you need to merger master branch or cherry pick IDEMPIERE-4537 from master

you should run with -DupdateRepository=true also, because you already generate localRepository without org.apache.commons.math3

**Comment by CarlosRuiz-globalqss** [comment]
Hi @hengsin - the math3 dependency was solved by @hieplq in the penultimate commit.

My test was successful in a clean "git clone", not sure if that fails if you try it in your current repository, maybe that affects?

**Comment by hengsin** [comment]
hi @hieplq , don't realise your branch is behind master, will do the merge and try again. also, the first run is real slow, can we make this optional behind a flag ?

**Comment by hieplq** [comment]
i don't make merger because i worry when merger back to master hard to squash but seem i'm wrong

by my test first run isn't slow than before much (about 1,2 minute only)

**Comment by hieplq** [comment]
i report test result [here](https://idempiere.atlassian.net/browse/IDEMPIERE-4535?focusedCommentId=46654&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-46654)

**Comment by hengsin** [comment]
works after run with -DupdateRepository=true. so this is necessary when there's upstream changes ? if yes, I think that might be an issue.

**Comment by hieplq** [comment]
it don't need update for every upstream change just in case artifact on org.idempiere.p2.targetplatform.target change then we need to -DupdateRepository=true to update localRepository also update org.idempiere.p2.targetplatformlocal.target

**Comment by hengsin** [comment]
hi @hieplq , that's kind of problematic. When there's artifact changes, your mvn verify will fail after git pull and it is not obvious what cause the error and how to fix it.

**Comment by hieplq** [comment]
i think about solution
sequenceNumber of targetPlatform is identify, can write down it to tracking file at localRepository after that groovy can check on it and write message to console

for CI can use shell script to check it to choose correct parameter

**Comment by CarlosRuiz-globalqss** [comment]
Hi @hengsin and @hieplq - any news about this?

There are conflicting files to solve at this moment - but also I understand the discussion is still open about the best approach.

**Comment by CarlosRuiz-globalqss** [comment]
Closing after 81 days of inactivity

**Pull request closed without merging**
