### PR TITLE
IDEMPIERE-5455 Use Multi-Select parameters in Info Windows

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
https://idempiere.atlassian.net/browse/IDEMPIERE-5455

### CODE REVIEW

**Comment by CarlosRuiz-globalqss** [comment]
it works fine for the selection, but the grid is not displaying the Business Partner.

**Comment by hengsin** [comment]
[pr1536.patch.txt](https://github.com/idempiere/idempiere/files/9835199/pr1536.patch.txt)
- fixed display for bp column

**Comment by CarlosRuiz-globalqss** [comment]
Thanks @hengsin - works fine

**Review by hengsin — APPROVED** [review]
tested

**Pull request merged**
