### PR TITLE
IDEMPIERE-6256 Get image through url from attachment

### PR DESCRIPTION
**Pull request by hengsin**
https://idempiere.atlassian.net/browse/IDEMPIERE-6256

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [x] I have tested the direct scenario that my code is solving
- [x] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [x] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

### CODE REVIEW

**Review by PeterTakacs300 — CHANGES_REQUESTED** [review]
Hi @hengsin 

tested 2 use cases in Garden Word, one of them failed:

1. Order Detail report
    - url: attachment:m_product/*.png,@M_Product_ID@
    - test result: **PASS**
2. Order Header (order document print)
    - sales order window -> print button
    - print format: Order Header
    - url: attachment:c_order/*.png,@C_Order_ID@
    - test result: **FAIL**
      - in PDF the image is not visible (HTML and DataTable seems OK)
      - on any type, when I refresh the report, in the console I see the following log: `ImageElement.<init>: Image is NULL [478]` - even if there is only one line in the report and the image is there, not sure what causes this log then

> [!NOTE]
> I think later in the documentation it needs to be mentioned that the context variable is case sensitive. If not explained, it must not be clear for many users, why the table name is not case sensitive, but the record id is

**Comment by hengsin** [comment]
hi @PeterTakacs300 , fix pushed for the order header issue. Context variable is case sensitive in iDempiere, it is not something specific for this ticket and doesn't needs to be specifically documented for this ticket.

**Review by PeterTakacs300 — APPROVED** [review]
I see, ok.

My tests passed successfully

**Comment by hengsin** [comment]
tested by @PeterTakacs300

**Pull request merged**
