### PR TITLE
IDEMPIERE-4459 Info Window Customization

### PR DESCRIPTION
**Pull request by igorpojzl**
https://idempiere.atlassian.net/browse/IDEMPIERE-4459

Implemented Info Window Customization, Info Columns only.
Please do a Code Review if this approach is acceptable.

- [ ] **TODO**: Info Related will be implemented later, if current implementation is accepted for Core.
- [ ] **TODO**: Apply new Caching.

### CODE REVIEW

**Review by globalqss — CHANGES_REQUESTED** [review]
The migration scripts threw errors applied to a clean database.

Cannot test functionality without completing the scripts.

Please fix (remember to fix always both postgresql and oracle).

**Comment by norbertbede** [comment]
strange. we created all scripts on clean idempiere seed db. review tomorrow, fix it.

**Comment by igorpojzl** [comment]
Updated Migration Scripts. Oracle Migration script was not updated 202009161020_IDEMPIERE-4459.

**Comment by norbertbede** [comment]
@globalqss we fixed migration scripts for Postgres, minimally we can start to validate code and functionality. We need help with oracle, probably I will try to find answers, what I did wrong when I created the windows.

**Comment by norbertbede** [comment]
@globalqss just notifying the migration script was fixed. thanks for review

**Comment by CarlosRuiz-globalqss** [comment]
Hi @norbertbede / @igorpojzl 

I worked some hours on this - making the postgresql script work - and synchronizing it with the oracle script.

The result is in the patch [IDEMPIERE-4459_fixes.txt](https://github.com/idempiere/idempiere/files/5287123/IDEMPIERE-4459_fixes.txt)

To do this I re-generated the tables from within iDempiere (this way it generates script for postgresql and oracle) - and after that re-generated the model X/I classes.

The result was not good.

I think the scripts are too messy to be integrated - there are missing columns on dictionary that came on your script, like:
ad_userdef_info_related.displaylength
ad_userdef_info_related.isreadonly
ad_userdef_info_related.issinglerow
ad_userdef_info_related.readonlylogic
ad_userdef_info_column.ad_element_id
ad_userdef_info_column.ad_infocolumn_uu
ad_userdef_info_column.columnname
ad_userdef_info_column.entitytype
ad_userdef_info_column.isidentifier
ad_userdef_info_column.iskey
ad_userdef_info_column.issameline
ad_userdef_info_column.queryfunction
ad_userdef_info_column.selectclause

And there is also one column that is in dictionary, but was not in the script of the create table:
ad_userdef_info_column.ad_userdef_info_id

I also noticed in the script there are insert into these tables:
AD_InfoColumn
AD_InfoRelated
AD_InfoWindow
AD_UserDef_Tab
AD_UserDef_Win

This is unexpected as these tables doesn't have relation with this ticket.

Conclusion - I think the script is too messy to be fixed.
Probably is better to re-generate it from zero, this can be done using 2pack to export ALL the new structures (elements, tables, columns, windows, tabs, fields, valrule, references, etc) related to the ticket, and importing that 2pack into a clean database with the "Log Migration Script" enabled.
If you don't know how to do that - if you upload the 2Pack in the ticket I can help.

Regards,

Carlos Ruiz

**Comment by norbertbede** [comment]
thanks for your review. 

looks I did some critical mistakes. I want to save time beginning but make trouble. good lesson.

what i did
1. I created 90% of the table structure in SQL editor - then I create tables and create columns from table.  (If I understand well, then migration doesn't create alter table) - this is Igor effort manually fix.
2. instead create a feature with local ID's module - as you suggest where (not met before) http://wiki.frei-bier.org/wiki/ID_Management - I record each step by recording pieces of changes then it makes a huge mess...
3. I added tabs as demo data - you wrote above. i assumed otherwise hard to test would be in place to extend it.

we will try tomorrow to make 2 pack then log migration scripts.
norbert

**Comment by igorpojzl** [comment]
Updated Java Models and Migration Scripts, i used Pack In.

**Comment by norbertbede** [comment]
@CarlosRuiz-globalqss  please help us with review., we have create new migration scripts as you suggested by 2pack export/import with clean seed database.

norbert

**Comment by CarlosRuiz-globalqss** [comment]
Hi @igorpojzl - can you please apply the patch:
[259_diff.txt](https://github.com/idempiere/idempiere/files/5314984/259_diff.txt)

Tested the migration scripts in postgresql and oracle with this patch - both seems to be working fine.

After that we can start testing.

Regards,

Carlos Ruiz

**Comment by igorpojzl** [comment]
I applied Patch. There is one TODO, If this solution is good, add new caching to this Info Window Customization.

**Comment by CarlosRuiz-globalqss** [comment]
Comments in ticket.

**Comment by norbertbede** [comment]
comments and 2pack in the ticket.

**Comment by CarlosRuiz-globalqss** [comment]
Hi @igorpojzl - please apply the patch 
[IDEMPIERE-4459_fixes_2.txt](https://github.com/idempiere/idempiere/files/5361404/IDEMPIERE-4459_fixes_2.txt)
that solves most of the problems I made in the ticket.

I'll add more comments in the ticket about my peer review.

**Comment by norbertbede** [comment]
@carlosruiz we have done the suggested change and commit PR. 

- window customization (name desc, comment) tab works
- related tab - seq, renaming + bonus Displayed = Y/n
- fix - the menu is translated in all languages - changed behaviour

new caching we will implement after this is accepted into the core. (do now want mix here)

**Comment by CarlosRuiz-globalqss** [comment]
https://mattermost.idempiere.org/idempiere/pl/o1t5qshppjgmfyc81si7kfhscy

**Comment by norbertbede** [comment]
@CarlosRuiz-globalqss, changes

- removed isDisplayed - as we agreed in mattermost
- added DisplayLogic ad1. to basic info window and ad2. to info window customization (tested basic cases)
- bugfix - column sequence works now.

please review
norbert

**Comment by CarlosRuiz-globalqss** [comment]
Thanks @igorpojzl - this is tested successfully, just some minor changes pending, can you please apply the following patch:
[IDEMPIERE-4459_fixes_3.txt](https://github.com/idempiere/idempiere/files/5386507/IDEMPIERE-4459_fixes_3.txt)

**Comment by norbertbede** [comment]
@CarlosRuiz-globalqss  patch applied. n

**Review by CarlosRuiz-globalqss — APPROVED** [review]

**Pull request merged**
