### PR TITLE
IDEMPIERE-6116 - Implement escape sequence in Env parseVariable and parseContext methods

### PR DESCRIPTION
**Pull request by PeterTakacs300**
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-6116

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [ ] I have made corresponding changes to the documentation as follows:
  - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
  - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

### CODE REVIEW

**Review by CarlosRuiz-globalqss — CHANGES_REQUESTED** [review]
please see comments at
https://idempiere.atlassian.net/browse/IDEMPIERE-6116?focusedCommentId=50785

**Comment by hengsin** [comment]
hi @CarlosRuiz-globalqss , this looks good to me, WDYT ?

**Review by CarlosRuiz-globalqss — CHANGES_REQUESTED** [review]
I have not tested yet the approach, but just ran the test org.idempiere.test.base.EnvTest.testParseVariable() and is failing.

**Comment by CarlosRuiz-globalqss** [comment]
Also, I think is worthy to add unit tests for more cases, like combining emails with context variables.

**Comment by norbertbede** [comment]
would be great to finish this issue.

**Review by hengsin — APPROVED** [review]
looks and pass unit test.

**Comment by PeterTakacs300** [comment]
Hi @CarlosRuiz-globalqss, does it look ok to you as well, or does it need some changes still?

**Comment by hengsin** [comment]
hi @CarlosRuiz-globalqss , can you please review this ? This is blocking https://idempiere.atlassian.net/browse/IDEMPIERE-4827

**Comment by CarlosRuiz-globalqss** [comment]
Hi @PeterTakacs300 , @hengsin , @norbertbede 

Re-reading this.

1 - Heng Sin suggested in ticket the solution #2 - which I agree is maybe the correct way to go, but the pull request is not implementing that or the changes on MMailText and MAllocation
I see there was a commit with those changes, but it was reversed.
I think the keepEscapeSequence is the right solution because I find it hard to explain/document that the number of @ reqired is not fixed, for one @ in MAllocation you need four @ - but for one @ in MMailText you need six @
For consistency I think is better to document just that you need @@ as replacement - and document that in custom code you need to take care of the extra keepEscapeSequence parameter.

2 - documentation page is missing

3 - Peter offered to write extra test cases for Env.parseContext but they are missing too.  I think is important because we are just testing the "white case" but not testing the backward compatibility with older tests.  And ideally the tests must cover more cases, not simply test@@gmail.com - but also strings starting or ending with @@, or strings with more than one @@ in the middle.

Regards,

Carlos Ruiz

**Comment by hengsin** [comment]
hi @CarlosRuiz-globalqss ,

I don't understand what do you means by the number of @ require is not fix. The idea is to get '@', you use '@@' and to get '@@', you use '@@@@'. AFAIU, the number of require @ is fix.

Regards,
Low

**Comment by PeterTakacs300** [comment]
Hi,

Yes it should be fixed as Heng Sin said, we followed the general "escape character logic" here, I mean to put the escape character before every character we want to keep unchanged. Like in Java strings you put backslash e.g. before every double quote, or in sql '' is used to escape single quotes as far as I know. So our solution fits into this logic.

**Comment by CarlosRuiz-globalqss** [comment]
I'm referring to my test case described at:
https://idempiere.atlassian.net/browse/IDEMPIERE-6116?focusedCommentId=50785
described after "Create a Mail Template with this Text:" ...

I just repeated the test case and is still failing

**Comment by hengsin** [comment]
> I'm referring to my test case described at: https://idempiere.atlassian.net/browse/IDEMPIERE-6116?focusedCommentId=50785 described after "Create a Mail Template with this Text:" ...
> 
> I just repeated the test case and is still failing

Ok, that needs to be fixed. The solution should be simple, just replace '@@' with some special character string before the multiple parse call and replace the special character string with '@' after the multiple parse call.

**Comment by hengsin** [comment]
hi @PeterTakacs300 , I think I make a mistake earlier to ask you to revert the keepEscapeSequence changes, we need to restore that for the multiple parse call use case (the mmailtext use case above). It seems more structural that way then the replace with custom character string approach.

**Comment by hengsin** [comment]
replace by https://github.com/idempiere/idempiere/pull/2503

**Pull request closed without merging**
