### PR TITLE
IDEMPIERE-6113 : Date Range boxes on Info Window are too small

### PR DESCRIPTION
**Pull request by uthadehikaru**
https://idempiere.atlassian.net/browse/IDEMPIERE-6113

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [ ] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [x] I have tested the direct scenario that my code is solving
- [ ] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

### CODE REVIEW

**Review by CarlosRuiz-globalqss — CHANGES_REQUESTED** [review]
I understand the patch is to make the size of the labels shorter, but that's not solving the problem of the date range being too small.

It kind of creates a different issue too, as for example the label "EMail Address" becomes two lines instead of one.

**Comment by CarlosRuiz-globalqss** [comment]
@uthadehikaru - I tried the following patch (on top of yours):
[pr2320PR.patch.txt](https://github.com/idempiere/idempiere/files/15051910/pr2320PR.patch.txt)

For me it's working fine, can you please confirm?

**Comment by uthadehikaru** [comment]
> @uthadehikaru - I tried the following patch (on top of yours): [pr2320PR.patch.txt](https://github.com/idempiere/idempiere/files/15051910/pr2320PR.patch.txt)
> 
> For me it's working fine, can you please confirm?

hi Carlos. the layout is not look nice for me from UI view. but yes it's solve the problem. i add minor fix to set the vertical align top on row so it make the view better.

[PR2320.patch.txt](https://github.com/idempiere/idempiere/files/15056000/PR2320.patch.txt)

**Comment by hengsin** [comment]
If we are to make code changes, it make more sense to move all/any as the last query parameter. Can't imagine that's more difficult than what your guys has posted above.
Also, as it is, it is possible to improve the situation with some css changes (should move the dash style call to css too):
Screenshot from 2024-04-22 12-05-56
Screenshot from 2024-04-22 12-07-19

**Comment by hengsin** [comment]
Patch to move All/Any to bottom of parameter grid:
[MoveAllAny.patch.txt](https://github.com/idempiere/idempiere/files/15057570/MoveAllAny.patch.txt)

**Comment by CarlosRuiz-globalqss** [comment]
I combined all your ideas and came up with this commit:
https://github.com/idempiere/idempiere/pull/2320/commits/7cdacb44e17a8c0ba332687372a79c31daf64402

It position the All/Any in a fixed position always as last parameter in the same last row if there is space.

I also changed the extra column at the right to use just 4% of the screen, and changed the width for labels and fields to be calculated depending on the number of columns, fields are double size as labels.

I removed the dash in the middle as it seems unnecessary - I think the PlaceHolders are enough to explain is a range.

I also added back buttons for numberbox and datebox.

**Comment by uthadehikaru** [comment]
i checked the latest change. the date range is not show full even after i hide the help panel. the previous layout even not looks good but user can see the date range in full view. there is still space on left and right side that can used to maximize the field. 
image

**Comment by norbertbede** [comment]
that is worst, you lost a row.

**Comment by hengsin** [comment]
> that is worst, you lost a row.

hi @norbertbede , what would you prefer here ? keep all/any as it is (perhaps we can reduce the space allocated to it and shorten the text label) and apply the css changes I posted above ?

**Comment by CarlosRuiz-globalqss** [comment]
> that is worst, you lost a row.

you lose a row when the last row is fully occupied, but the problem here is about trying to get more width - so gaining a column is good for the purpose.

In mobile you have very little width, but you can scroll down to many rows.

**Comment by hengsin** [comment]
hi @CarlosRuiz-globalqss , what about letting the grid to size by content instead:
[2320.patch.txt](https://github.com/idempiere/idempiere/files/15070774/2320.patch.txt)

**Comment by uthadehikaru** [comment]
i tried maximize the possible width for editor. looks good on me
image
[patch.diff.txt](https://github.com/idempiere/idempiere/files/15071671/patch.diff.txt)

**Comment by CarlosRuiz-globalqss** [comment]
> hi @CarlosRuiz-globalqss , what about letting the grid to size by content instead: [2320.patch.txt](https://github.com/idempiere/idempiere/files/15070774/2320.patch.txt)

Hi @hengsin, I tried your patch and it looks almost good except:
* in my Business Partner Info it creates an horizontal scrollbar always - my test info has date range and TotalOpenBalance as numeric range
* almost all info windows looks OK except Asset Info, there is a multi-selection Business Partner there, and it creates a mini textbox where content is barely visible

BTW, moving the All/Any to the last row has a very good effect in mobile, before that change the All/Any consumes half of the mobile screen, after that it looks much better.

**Review by hengsin — APPROVED** [review]
tested

**Review by CarlosRuiz-globalqss — APPROVED** [review]
tested too

**Pull request merged**
