### PR TITLE
IDEMPIERE-4499:zk9.5 - Popup menu disappear quickly for buttons on th…

### PR DESCRIPTION
**Pull request by hieplq**

### CODE REVIEW

**Comment by hengsin** [comment]
I tested this but I'm not sure what have been improved here - it is still a poor experience where the submenu for "Private Record Lock" popup after the menu popup have been closed. It will be good if it can be make behave the same as the overflow popup for mobile where the main popup menu stay open.

**Comment by hieplq** [comment]
it's not improve, it's work-around for zk issue
agree moment design isn't great, it should is sub-menu as Norbert do

**Comment by CarlosRuiz-globalqss** [comment]
Tested successfully too - agree would be better if the behavior is similar to mobile, if is too hard to implement, then the workaround is OK.

**Review by CarlosRuiz-globalqss — APPROVED** [review]

**Comment by hengsin** [comment]
lets hold this open first, I will try to build an alternative that uses the same mobile implementation.

**Comment by hengsin** [comment]
created the alternative implementation that uses the existing mobile overflow popup #329 , please compare and pick one

**Comment by CarlosRuiz-globalqss** [comment]
replaced by https://github.com/idempiere/idempiere/pull/329

**Pull request closed without merging**
