### PR TITLE
IDEMPIERE-1709 / IDEMPIERE-2624 Cant confirm 0 qty on Movement Confir…

### PR DESCRIPTION
**Pull request by globalqss**
…mation

Implement void for movement confirm

https://idempiere.atlassian.net/browse/IDEMPIERE-1709

### CODE REVIEW

**Comment by hengsin** [comment]
hi @globalqss , I'm able to Complete the Movement document after I've voided the Movement Confirmation document. Is that the expected behaviour ?

**Comment by globalqss** [comment]
Thanks @hengsin - I added code to void the inventory move when the confirmation is voided.

**Comment by globalqss** [comment]
Hi @hengsin - pushed a third commit because during tests found that MInOut is suffering from the same catch-22 situation, cannot void the InOut because there are confirmations, cannot void the confirmation because the InOut is not void.

As I saw the implementation here was different and it was to void the confirmations when the InOut is void, so I added a bit of code to restore that flow.

**Review by hengsin — APPROVED** [review]
good to go

**Pull request merged**
