### PR TITLE
IDEMPIERE-5482 - Field Style Scope HTML Element

### PR DESCRIPTION
**Pull request by PeterTakacs300**
JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5482

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

### CODE REVIEW

**Review by hengsin — CHANGES_REQUESTED** [review]
this design is inappropriate , ad_style can be applied to place more than just info window cell.

**Comment by PeterTakacs300** [comment]
Hi @hengsin, would this approach be acceptable, if we would implement it in other places where AD_Style can be applied?

**Comment by hengsin** [comment]
hi @PeterTakacs300, it make more sense to just add it to info window. It is not appropriate to just assume span and table cell works for all places where ad_style is being used.

**Comment by PeterTakacs300** [comment]
Hi @hengsin, we came up with a slightly different approach.

After research, I've noticed that when you switch to grid view in regular windows, the ad_style is applied already properly, since there is always a span in the td element.

The new approach: we are trying to unify the application of ad_style based on this window-grid view:
- the code always adds a wrapper span in info window and in reports, when we want to apply ad_style (from info column and from print format item)
- We've removed the AD_StyleScope field, since it is useless with this new approach

In this case, the ticket name and description should be also updated.

**Comment by hengsin** [comment]
[pr1572.patch1.txt](https://github.com/idempiere/idempiere/files/11201390/pr1572.patch1.txt)
- shouldn't call mstyle.get if ad_fieldstyle_id is 0.

**Comment by PeterTakacs300** [comment]
Thanks @hengsin, tested and applied

**Review by hengsin — APPROVED** [review]
tested

**Pull request merged**
