### PR TITLE
IDEMPIERE-4977 IDempiere Homepage using custom image path failed to l…

### PR DESCRIPTION
**Pull request by uthadehikaru**
…oad the image

this is a bug fix for this issue. method to encode should be encodeToString instead encode.

### CODE REVIEW

**Review by hengsin — CHANGES_REQUESTED** [review]
According to https://stackoverflow.com/questions/5641303/base64url-in-java, the proper fix should be Base64.getUrlEncoder().withoutPadding().encodeToString(data) instead.

**Review by CarlosRuiz-globalqss — CHANGES_REQUESTED** [review]
tested

**Comment by CarlosRuiz-globalqss** [comment]
> According to https://stackoverflow.com/questions/5641303/base64url-in-java, the proper fix should be Base64.getUrlEncoder().withoutPadding().encodeToString(data) instead.

Hi @hengsin - I tested the solution from @uthadehikaru and it worked fine.

The change suggested in stackoverflow didn't work - it shows blank images.  The getUrlEncoder works just for URLs and filenames and here it is encoding a byte image.

So, I think is OK to push this as it is.

**Comment by hengsin** [comment]
alright, my mistake, the patch is good.

**Review by hengsin — APPROVED** [review]

**Pull request merged**
