### PR TITLE
IDEMPIERE-4213 Window Toolbar attached processes are doesn't validate…

### PR DESCRIPTION
**Pull request by globalqss**
… role access

https://idempiere.atlassian.net/browse/IDEMPIERE-4213

### CODE REVIEW

**Comment by igorpojzl** [comment]
Hi, i tested this PR. It is Working.
I have one question. This solution will apply on Menu Buttons too. So for example if User do not have Access to Complete Sales Order, in Sales Order Window he will not see Document Action button in Grid too. Is this functionality desirable?
Screenshot 2020-09-21 at 12 59 58

**Comment by hengsin** [comment]
I guess that could cause some confusion since we do have access control for
document action too.

**Comment by globalqss** [comment]
The permissions for document action is for the options shown - so, it is about if a user can Complete/Void ... etc

I think is OK if the button is not shown when the user doesn't have access to the process.

I still managed the case if we want to show the button read-only, then you can define the access to the process as read-only.

**Comment by globalqss** [comment]
In other words:

The actual behavior is like this:

- if the user doesn't have access (or just read-only access) to the process - the button is shown and active, when the user pushes the button and select complete then an error is thrown: "You cannot access process [Process Order] with your role : GardenWorld User"

- if the user have access to the process, but doesn't have access to any document action - then the button is shown and when the user pushes the button it doesn't do anything - not even open the dialog

With this patch:

- if the user doesn't have access to the process - the button is not shown

- if the user has read-only access to the process - the button is shown disabled

- the behavior based on document action was not modified

So, I think in terms of usability is better - you have the two options - hide it, or show it disabled - what I think is bad on usability is showing a button active that is going to throw an error to the user when pushed.

**Review by hengsin — APPROVED** [review]
tested by Igor and Carlos

**Pull request merged**
