### PR TITLE
IDEMPIERE-4819 Private Lock - Allow Unlock other users Private Records

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
https://idempiere.atlassian.net/browse/IDEMPIERE-4819

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [x] I have tested the direct scenario that my code is solving
- [x] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by hengsin** [comment]
hi @CarlosRuiz-globalqss , while the code looks fine, it is a use case that should be validated by @norbertbede. My only concern is whether this can be perceived as a security back door.

**Comment by CarlosRuiz-globalqss** [comment]
Hi @hengsin - IMO not a backdoor, is a missing functionality.

Users can mistakenly lock records and the tenant admin doesn't have any ability to look for that, is just visible using SQL (just the implementor or IT)

The Where clause in the Tab is to prevent users from seeing records they don't have permission to see or fix.
Also the beforeSave validation is to prevent being used as a backdoor (for example disabling a Private Record from REST web services).

**Comment by CarlosRuiz-globalqss** [comment]
Hi @hengsin 

I documented this feature at:
https://wiki.idempiere.org/en/NF11_Private_Access_Window

If you find this OK I think there is no need to wait for @norbertbede approval.

This is not intended to solve Norbert's issue but to solve a missing feature on iDempiere.

Is it OK to move it ahead?

**Comment by norbertbede** [comment]
hi, i'm quite busy, but i can take a look today. if you are sure, no need to wait for me. n

**Comment by hengsin** [comment]
hi @CarlosRuiz-globalqss ,

I think we need to add 2 things here:
- notify user that their "Privately Locked" record have been unlocked by other
- need to let user know that their "Privately Locked" can be unlocked by other with "Personal Access" privilege. Perhaps a message or some documentation update.

**Comment by CarlosRuiz-globalqss** [comment]
Hi @hengsin,

>     * notify user that their "Privately Locked" record have been unlocked by other

I don't agree that's needed.

This is usually a tenant admin person or an IT person solving a problem created by a non-admin user.  Just that at this moment is done via SQL and now they'll be able to do it directly in the app.

Usually actions from an administrator don't need to be notified to the non-admin users.

For example the use case described by @norbertbede doesn't apply:
"when user created privatelock (role has enabled private lock feature) of a record, only the same user able to unlock it. If user leave company or on holiday or in our case users makes lock in e-commerce portal -  nobody able to unlock it"

>     * need to let user know that their "Privately Locked" record can be unlocked by other with "Personal Access" privilege. Perhaps a message or some documentation update.

I'm not sure about this need.

The fields Personal Lock and Personal Access are documented, maybe the phrasing of the Personal Access help could be changed to:
"Users of this role have access to all records locked as personal, **and they can unlock records if they have access to the Private Access window**"


Anyways, if this is not good for core is very easy to make it a plugin instead.

**Review by hengsin — APPROVED** [review]
looks good

**Pull request merged**
