### PR TITLE
IDEMPIERE-5720 Multi select product on orders is broken

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [x] I have tested the direct scenario that my code is solving
- [x] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by victorsuarezis** [comment]
Hello Carlos. I am testing. But I have NullPointer exception, the problem is in InfoWindow Class, with method onRestoreSelectedItemIndexInPage, line 2953.

**Comment by CarlosRuiz-globalqss** [comment]
> Hello Carlos. I am testing. But I have NullPointer exception, the problem is in InfoWindow Class, with method onRestoreSelectedItemIndexInPage, line 2971.

Thanks @victorsuarezis - this is a different bug, what you're looking is at https://github.com/idempiere/idempiere/pull/1834

**Comment by victorsuarezis** [comment]
I corrected it like this:

```java
@Override
	public boolean onRestoreSelectedItemIndexInPage(Integer keyViewValue, int rowIndex, Object oRow)
	{
		//if(hasEditable && temporarySelectedData != null)
		if(hasEditable && temporarySelectedData != null && !temporarySelectedData.isEmpty())  // Fixed Bug
		{
			
			cacheOriginalValues(rowIndex);
			
			@SuppressWarnings("unchecked")
			List<Object> row = (List<Object>)oRow;
			List<Object> originalSelectedRow = temporarySelectedData.get(keyViewValue);
			ListModelTable model = contentPanel.getModel();
			
			// While restoring values we dong want to trigger listeners
			model.removeTableModelListener(this);
			
			for(int i=0; i < columnInfos.length; i++)
			{
				if(columnInfos[i].isReadOnly() == false) // Only replace editable column, in case some other data changed on db
				{
					Object obj = originalSelectedRow.get(i);
					model.setValueAt( obj, rowIndex, i);
				}
			}
			
			// Restore isSelected status on IDColumn
			Object id = (IDColumn)row.get(0);
			
			if(id instanceof IDColumn)
			{
				IDColumn idc = (IDColumn)id;
				idc.setSelected(true);
			}
			
			// Restore listners
			model.addTableModelListener(this);
		}

		return super.onRestoreSelectedItemIndexInPage(keyViewValue, rowIndex, oRow);
	}
```

**Comment by victorsuarezis** [comment]
Ok, I understand. Anyway I tried with the corrections you made to this class, it's ok, I have no errors.
Thank you so much

**Review by victorsuarezis — APPROVED** [review]

**Review by hengsin — APPROVED** [review]
tested

**Pull request merged**
