### PR TITLE
IDEMPIERE-5428 Implemented Single Sign-On using MSAL

### PR DESCRIPTION
**Pull request by Effecitech**
# Pull Request Checklist

## Checklist:

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

[Single Sign-On Documentation.pdf](https://github.com/idempiere/idempiere/files/9949394/Single.Sign-On.Documentation.pdf)

### CODE REVIEW

**Comment by hengsin** [comment]
hi @Effecitech , where possible, we prefer to update the target platform instead of using embedded jar (also, some of the library like jackson and slf4j is already part of the existing target platform).

**Comment by Effecitech** [comment]
I have updated the target with the dependencies

**Comment by hengsin** [comment]
hi @Effecitech , you need to update maven.locations.xml,
see https://wiki.idempiere.org/en/Building_iDempiere_by_tycho#update_.5Bidempiere-source.5D.2Forg.idempiere.p2.targetplatform.2Forg.idempiere.p2.targetplatform.target (From 9)

**Comment by Effecitech** [comment]
I have updated the maven.locations following the steps in the page you gave me. I don't kown if I did it correctly but the project build an run fine

**Comment by CarlosRuiz-globalqss** [comment]
Closing this pull request as is covered in https://github.com/idempiere/idempiere/pull/1571

**Pull request closed without merging**
