### PR TITLE
IDEMPIERE-4297 Improve test data / fix some wrong data in GardenWorld seed

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
Coming from @cboecking review here:
https://mattermost.idempiere.org/idempiere/pl/y9rkthgmrjnt7npiai3dhukf4e

### CODE REVIEW

**Comment by tony-tspc** [comment]
Oracle script is missing SET SQLBLANKLINES ON & SET DEFINE OFF

**Comment by CarlosRuiz-globalqss** [comment]
> Oracle script is missing SET SQLBLANKLINES ON & SET DEFINE OFF

That's not a problem in this script - we added that to the script generator because some scripts fail when they have new line inside quotes, or have the @ within the statement.

In this case, this manual script doesn't have any of those.

**Comment by tony-tspc** [comment]
Thanks @CarlosRuiz-globalqss, got so used to seeing the statements, forgot the reason behind them. 
I tested the Postgresql script and is working as expected.

**Comment by CarlosRuiz-globalqss** [comment]
Approving as confirmed by @tony-tspc

**Pull request merged**
