### PR TITLE
Idempiere 4773

### PR DESCRIPTION
**Pull request by matheus-marcelinux**
https://idempiere.atlassian.net/browse/IDEMPIERE-4773

Following the Heng Sin's approach, i've implemented mapped factory for forms, cause i needed it to my plugins, keeping them uniform. I didn't write test cases in org.idempiere.test, but i created in my workspace a plugin following the three approachs described in ticket above and it works fine.

### CODE REVIEW

**Review by hengsin — CHANGES_REQUESTED** [review]
please remove all the unnecessary white space only changes.

**Comment by matheus-marcelinux** [comment]
Hi @hengsin, during this weekend i'll do this. Thanks.

**Comment by CarlosRuiz-globalqss** [comment]
Hi @matheus-marcelinux - this is important for readability of the code being peer reviewed, when the pull request does additional changes is hard to trace what exactly is being modified, and what is just cosmetic things.

**Comment by hengsin** [comment]
replace by pull/688

**Pull request closed without merging**
