### PR TITLE
IDEMPIERE-6083 Add Customize Grid View form to Window Customization

### PR DESCRIPTION
**Pull request by hengsin**
https://idempiere.atlassian.net/browse/IDEMPIERE-6083

- added "Customize Grid View" menu item to Window Customization > Tab Customization > Process Toolbar (The Gear Toolbar Button) popup menu.

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [x] I have tested the direct scenario that my code is solving
- [x] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [x] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

### CODE REVIEW

**Comment by CarlosRuiz-globalqss** [comment]
Hi @hengsin - the TabEditor tries to avoid writing many records in AD_UserDef_Field, when you change the position of one field in the TabEditor on tenant the SeqNo of that field is calculated ending with 5, so if you move a field between the fields 100 and 110, the SeqNo will be 105 (most of the time that works).  That avoids recalculating the SeqNo of many fields.

I tested change the position of one field on the grid for Sales Order, and it created 18 records with SeqNoGrid multiple of 10, would be better if it can behave similar to TabEditor, when moving a single field in the grid position it in the middle with a multiple of 5.

Does that sound OK?

**Comment by hengsin** [comment]
> Hi @hengsin - the TabEditor tries to avoid writing many records in AD_UserDef_Field, when you change the position of one field in the TabEditor on tenant the SeqNo of that field is calculated ending with 5, so if you move a field between the fields 100 and 110, the SeqNo will be 105 (most of the time that works). That avoids recalculating the SeqNo of many fields.
> 
> I tested change the position of one field on the grid for Sales Order, and it created 18 records with SeqNoGrid multiple of 10, would be better if it can behave similar to TabEditor, when moving a single field in the grid position it in the middle with a multiple of 5.
> 
> Does that sound OK?

Change push, please re-test.

**Comment by CarlosRuiz-globalqss** [comment]
> Change push, please re-test.

My test case:
Window Customization for:
Window -> Sales Invoice and Credit/Debit Note
Tab -> Invoice

* With _Tab Editor_ move the field _Sales Representative_ below _Document No_
  * The system creates one custom record with _Sequence_ 65 and _Grid Sequence_ 0 (0 means is unchanged)
* With _Customize Grid View_ move _Business Partner_ below _Document No_: two things wrong:
  * In _Customize Grid View_ the _Sales Representative_ is shown first (I guess because of the custom 0 which must be ignored)
  * it created 35 custom records - expected would be to have just one record for _Business Partner_

**Review by CarlosRuiz-globalqss — APPROVED** [review]
tested succesfully

**Pull request merged**
