### PR TITLE
IDEMPIERE-5057 Implement Deductible and non deductible input tax for …

### PR DESCRIPTION
**Pull request by hengsin**
…purchasing and costing

- Fix error when user change invoice/order line to use parent tax

https://idempiere.atlassian.net/browse/IDEMPIERE-5057

# Pull Request Checklist

## Checklist:

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have added unit tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

### CODE REVIEW

**Review by CarlosRuiz-globalqss — CHANGES_REQUESTED** [review]
Hi @hengsin - this is still not working as expected.

Test case in release-9:

* Create a Sales Order
  * BP = C&W
* Create an Order Line
  * Product = Azalea
  * Tax = GST/PST

At this point - when the order line is saved, the behavior is like this:

* release-9
  * Creates a record in Order Tax with the tax GST/PST
  * this record is deleted and replaced when completing the order with the children taxes

this pull request is not creating the GST/PST temporary record in Order Tax.

**Comment by hengsin** [comment]
hi @CarlosRuiz-globalqss , why must we create the temporary GST/PST record ?

**Comment by CarlosRuiz-globalqss** [comment]
> hi @CarlosRuiz-globalqss , why must we create the temporary GST/PST record ?

That record has been there since compiere times, I suppose is important for reporting before completing.

For example, printing the sales order in draft gets a wrong total without that record.

**Comment by hengsin** [comment]
The example cited is an confusing one - you means the order is suppose to print differently in draft and completed status ? That sounds strange to me.

**Comment by CarlosRuiz-globalqss** [comment]
Well, I think users print orders in draft to check if everything is OK before preparing or completing.

In this case the tax is not appearing when is a composite tax, and because of that the total of the order is printed wrongly too.

It has been always the case to create the parent tax record on save, and replace with the children on prepare/complete.

IMO would be better to create the children directly when saving, instead of a fake parent record that could lead to some rounding cents difference.  But I think is maybe for easiness of the code (or maybe performance?) that it has been saving the parent record instead of calculating on saving the line.

**Comment by hengsin** [comment]
ok, will check the printing issue.

**Review by CarlosRuiz-globalqss — CHANGES_REQUESTED** [review]
Hi @hengsin - I tested this successfully

Found two issues:

1 - there is conflict that can be solved with this patch:
[conflict.txt](https://github.com/idempiere/idempiere/files/9889057/conflict.txt)

2 - during the tests I noticed the taxes were printed strange in the order, verified and found there was a mismatch in the "Line" column between c_order_linetax_v and c_invoice_linetax_v
The following patch fixes that too:
[script.txt](https://github.com/idempiere/idempiere/files/9889064/script.txt)

Regards,

Carlos Ruiz

**Review by CarlosRuiz-globalqss — APPROVED** [review]

**Pull request merged**
