### PR TITLE
IDEMPIERE-4586 Update translation of Client to Tenant

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
https://idempiere.atlassian.net/browse/IDEMPIERE-4586

### CODE REVIEW

**Comment by nmicoud** [comment]
Hi @CarlosRuiz-globalqss,
I've just look at the change, not tested locally.

Some remarks:
- I see Placeholder is not updated. Is it intentional?
- Shouldn't we regenerate all I/X classes based on tables with AccessLevel using Client/Tenant to use the new 'label'?
- Shouldn't we regenerate all I to "fix" javadoc for public int getAD_Client_ID(); (Get Client => Get Tenant) - not a big deal as the 2nd line is "Client/**Tenant** for this installation.").

I'll make tests tomorrow

Regards,

Nicolas

**Comment by CarlosRuiz-globalqss** [comment]
>     * I see Placeholder is not updated. Is it intentional?

I just included script for tables/columns that are affected in the seed database, not for empty columns, or columns not containing the "client" word.

For extending this to non-core tables or custom values, I think is very easy to just copy the script and include your own tables/columns in a custom migration script.

>     * Shouldn't we regenerate all I/X classes based on tables with AccessLevel using Client/Tenant to use the new 'label'?
>     * Shouldn't we regenerate all I to "fix" javadoc for public int getAD_Client_ID(); (Get Client => Get Tenant) - not a big deal as the 2nd line is "Client/**Tenant** for this installation.").

I think is not necessary as they are just comments.

But thanks to your comment I noticed the impact of changing AD_Ref_List.Name is too big, I reverted this one from the scripts.

**Comment by hengsin** [comment]
Perhaps we should update the Updated column too so that it is easier to trace back which records have been updated.

What about those that maintain en as translation instead ?

**Comment by nmicoud** [comment]
Hi,

I've tested the script on both Oracle and PG, seems ok.
I didn't find in code "Client" which should be shown to users - and as you said, is ok to let "Client" if is comment.

Just found some descriptions that needs to be updated :
- AD_Client_ID element description is "Tenant/Tenant for this installation."
- Tenant window description is "Maintain Tenants/Tenants"
- Tenant tab description is "Tenant/Tenant Definition"
- Table AD_Client description is "Client/Tenant for this installation." ; so maybe an update is also needed here (or wait for the next run of SyncTerminology process?)

Regards,

Nicolas

**Comment by CarlosRuiz-globalqss** [comment]
@hengsin 
> Perhaps we should update the Updated column too so that it is easier to trace back which records have been updated.

Done - added a timestamp for the Updated column in all affected records.

> What about those that maintain en as translation instead ?

The script just cover what is in seed, for customizations is easy to use this script as a template and add more tables.
Also, the actual recommended setup doesn't require English as translation.


@nmicoud 
> Just found some descriptions that needs to be updated :

Thanks, added those, and one more found to the scripts.

**Comment by nmicoud** [comment]
Hi @CarlosRuiz-globalqss,
One last... CommitWarning field on AD_Tab (eg: on Tenant window, there is still "Initial Client Setup".

**Comment by CarlosRuiz-globalqss** [comment]
> One last... CommitWarning field on AD_Tab (eg: on Tenant window, there is still "Initial Client Setup".

Thanks @nmicoud - added

**Review by nmicoud — APPROVED** [review]
looks good

**Pull request merged**
