### PR TITLE
IDEMPIERE-4829 - Add SeqNoGrid on UserDefWindow

### PR DESCRIPTION
**Pull request by nmicoud**

### CODE REVIEW

**Comment by CarlosRuiz-globalqss** [comment]
Hi  @nmicoud - can you please move the migration scripts to folder i8.2z ?

**Comment by nmicoud** [comment]
hi @CarlosRuiz-globalqss  ; done

**Comment by nmicoud** [comment]
oops, wrongly closed :-/

**Review by CarlosRuiz-globalqss — APPROVED** [review]
tested

**Pull request merged**
