### PR TITLE
IDEMPIERE-4662 Some problems of sort at window before save

### PR DESCRIPTION
**Pull request by hengsin**
https://idempiere.atlassian.net/browse/IDEMPIERE-4662

### CODE REVIEW

**Comment by HideakiHagiwara** [comment]
Thank you very much.
Amazing speed!
:-D

And I found that this issue difficult for me.
orz

So, very Thanks again.

I am testing now.

So, I found a improvement point.
We may need improve GridTable#dataSave() method that near the line 1490 .
I met save Error After sort in spite of I did not save.

How to Reproduce

*I added a new record and sort.
*I edited a new record column after sort.
*And pushed Enter keyboard button . (not save)

When I pushed Enter keyboard button, Called Save process and Error.

best regards.

**Comment by hengsin** [comment]
Hi @HideakiHagiwara , I can't reproduce the "Enter and Save" issue you posted above.

**Comment by HideakiHagiwara** [comment]
Hi @hengsin,

Sorry for a lack of explanation for my reproduce.
I found that this case is a little sensitive to reproduce .

[For Example Sales Order]
*I added a new record and edit Description Field. Please Notice to edit field before sort.
*And Sort at Grid View.
*And I edited Description Field of a new record again after sort. Please Notice The row number of the newly added record must be changed.
*And pushed Enter keyboard button . (not save)
*And Display Error "Could not save record - Require unique data: - Please change information.:"
*But this Error display first time only.
*Pushed Enter keyboard button second time, Do not display this Error.

GridTable#dateSave() near line 1490.

`	public boolean dataSave (int newRow, boolean manualCmd)
	{
		if (log.isLoggable(Level.FINE)) log.fine("Row=" + newRow +
			", Changed=" + m_rowChanged + "/" + m_changed);  //  m_rowChanged set in setValueAt
		//  nothing done
		if (!m_changed && m_rowChanged == -1)
			return true;
		//  same row, don't save yet
		**if (newRow == m_rowChanged)    //Passed this Logic when I pushed Enter key first time and go to save**
			return true;

		return (dataSave(manualCmd) == SAVE_OK);
	}   //  dataSave
`

When I edited the description field after sorting and pressed Enter key, it passed this "if (newRow == m_rowChanged)" check logic. and called dataSave() method 

best regards,

**Comment by hengsin** [comment]
alright, thanks for the detail instructions. reproduce fix now, please re-test.

**Comment by HideakiHagiwara** [comment]
Hi @hengsin,

I am testing now.

It seems good.

But I think this may be a little bit difference to our ideal that we talked about JIRA ticket.
When I sorted, I was saved automatically or displayed fill mandatory Error.

I think that our ideal is to do not save when sort.
But I think to save before sort is not bad.

best regards,

**Comment by hengsin** [comment]
Hi @HideakiHagiwara , don't understand your last comments. My changes doesn't auto save after sort.

**Comment by HideakiHagiwara** [comment]
Oh I am very sorry.
I mistake to commit new patch with old my patch
I reconfirm now.

**Comment by HideakiHagiwara** [comment]
Thanks @hengsin !

I tested. I think there are no problems.
It seems our ideal.
:-D

Thanks again.

best regards

**Review by CarlosRuiz-globalqss — APPROVED** [review]
Approving with confirmation from @HideakiHagiwara

**Pull request merged**
