### PR TITLE
IDEMPIERE-5574 Drop Ship BPartner must have opposite IsSOTrx logic on Info Window

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
https://idempiere.atlassian.net/browse/IDEMPIERE-5574

## Checklist:

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by CarlosRuiz-globalqss** [comment]
Hi @hengsin - could you please peer review this approach.

I know it sounds hackish, but it works fine with a very little cost.

I was analyzing how to implement a "proper" solution, and we would need to know the name of the field that is triggering the info window, I imagine putting a context variable for that purpose and changing the default/display logic of the IsCustomer and IsVendor fields to behave different according to the column DropShip_BPartner_ID.
The way how Info Window is called at this moment is not passing the information of the caller field, so the change would become too big and I'm afraid potentially disruptive because it could have collateral effects.

**Comment by hengsin** [comment]
hi @CarlosRuiz-globalqss ,
- looks fine but will cause conflict with the active/inactive pr.
- after we incorporate the active/inactive pr, caller field is pass to info window.

**Comment by CarlosRuiz-globalqss** [comment]
OK, thanks for the review.

Let's wait then until IDEMPIERE-5573 is pushed and I'll update this patch here.

This is the modified patch:
[5574_over_5573.patch.txt](https://github.com/idempiere/idempiere/files/10744278/5574_over_5573.patch.txt)

I added some more logic to avoid working on other tables that maybe are not intended to behave that way.

**Comment by CarlosRuiz-globalqss** [comment]
Hi @hengsin - this is ready for review - merged this pull request with latest changes

**Pull request merged**
