### PR TITLE
IDEMPIERE-4413 Change Role, disfunction all keyboard shortcuts

### PR DESCRIPTION
**Pull request by hengsin**
Fix key listener error after change role

### CODE REVIEW

**Comment by hieplq** [comment]
solution on PR is ok it keep Keylistener when change to role

i attach my solution by fix javascript side, it don't conflict with this solution
now can consider my solution as improve on case we need to remove/re-add Keylistener

[0001-IDEMPIERE-4413-remove-client-side-handle-key-event.patch.txt](https://github.com/idempiere/idempiere/files/5097465/0001-IDEMPIERE-4413-remove-client-side-handle-key-event.patch.txt)

**Comment by hieplq** [comment]
after review patch @globalqss attach on ticket then i consider apply only my patch is better
1. it resolve issue report by Norbert
2. don't need worry what @globalqss mention, because Keylistener, HeaderPanel, UserPanel all be GC so don't need to call remove listen
3. it reset change role panel to same case we login from home and choose "Select Role"

**Comment by globalqss** [comment]
Hi @hengsin - I tested your commits and they are working fine.

However, I think the patch posted by @hieplq here:
[0001-IDEMPIERE-4413-remove-client-side-handle-key-event.patch.txt](https://github.com/idempiere/idempiere/files/5097465/0001-IDEMPIERE-4413-remove-client-side-handle-key-event.patch.txt)
seems like a cleaner solution, and possibly better for future in case somebody does something similar preserving the Keylistener object.

Or, it can be as Hiep suggested that we add the patch on top of this, however, according with my tests, the patch from Hiep alone is enough and looks like a good solution.

WDYT?

Regards,

Carlos Ruiz

**Comment by hengsin** [comment]
yeah, if that's working fine, it is a cleaner solution.

**Pull request closed without merging**
