### PR TITLE
IDEMPIERE-4639 simplify calls using saveCrossTenantSafeEx when possible

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
This is just helping for readability

### CODE REVIEW

**Comment by hengsin** [comment]
hi @CarlosRuiz-globalqss , please consider the following patch to address nested `saveCrossTenantSafeEx()` call (due to model validator or event handler).

[pr2073.patch.txt](https://github.com/idempiere/idempiere/files/13063184/pr2073.patch.txt)

**Comment by CarlosRuiz-globalqss** [comment]
> hi @CarlosRuiz-globalqss , please consider the following patch to address nested `saveCrossTenantSafeEx()` call (due to model validator or event handler).

Thanks @hengsin - integrated your patch and added it in the other method

**Comment by CarlosRuiz-globalqss** [comment]
390/390 unit tests passed

**Review by hengsin — APPROVED** [review]
looks good

**Pull request merged**
