### PR TITLE
IDEMPIERE-4801 Add IMediaView interface and Keikai implementation

### PR DESCRIPTION
**Pull request by hengsin**
Fix preview of xlsx not working at attachment viewer

https://idempiere.atlassian.net/browse/IDEMPIERE-4801

### CODE REVIEW

**Comment by d-ruiz** [comment]
Hi @hengsin, I'm not sure how to test this. 

I integrated the changes, uploaded an xls and an xlsx file to a record and I cannot preview it in the attachment dialog. Am I missing something?

grafik

grafik

Best regards,
Diego

**Comment by hengsin** [comment]
works fine for me. note that this is for master (8.2z) only.

**Review by d-ruiz — APPROVED** [review]
I tested it in 8.2z on Firefox and Chrome. Probably I'm missing something. Anyway it is a trivial fix, so good to go

**Comment by ralexsander** [comment]
Hi @d-ruiz I've tested it a couple weeks ago and got the same behavior you mentioned. I've noticed that the MIME type was not detected by WAttachment around line 438, perhaps you could check if the MIME type is correct in your scenario. 
Now with the latest code I could not reproduce the error anymore and everything seems to be working fine for me.

**Pull request merged**
