### PR TITLE
IDEMPIERE-5445 Implement multiplier and rounding for financial reports

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
https://idempiere.atlassian.net/browse/IDEMPIERE-5445

# Pull Request Checklist

## Checklist:

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

### CODE REVIEW

**Review by nmicoud — APPROVED** [review]
Hi 

I've made some tests and I didn't find any issue.

nb: I may not be the best tester here as I'm not a specialist of Financial Reports as I'm not using them outside of this particular customer ; and I'm not the one who sets them up.

Thanks

Nicolas

**Comment by CarlosRuiz-globalqss** [comment]
Thanks @nmicoud - can you please help with the wiki documentation?

I would like to know the opinion from Steven Sackett, I think this is not 100% aligned with what he recommended on forums.
Will ask him in the JIRA ticket.

**Comment by nmicoud** [comment]
OK, I'll write a wiki page (and delete the previous one) - trying to do this this week

**Comment by adaxa-steven** [comment]
pls see attached which tries to explain my point better.... 
[percent display error.pdf](https://github.com/idempiere/idempiere/files/9764383/percent.display.error.pdf)

also noticed that Nicolas's original problem may be handled by std functionality provided he is happy to have percentages displayed to the currency precision

**Comment by nmicoud** [comment]
Hi Steven,
My original issue (which was in fact a missing functionnality) was to be able to round percentage lines. (and only those kind of lines).
I haven't tested the pattern functionnality, and from what I see in you document, it should work in my case as I have only 2 decimals on currencies.
But if you need more than 2 decimal, a patch is needed to "force" to round percentage lines and let other ones "untouched"

**Comment by adaxa-steven** [comment]
also noted ... in the daily build in the report 'steven test' the value for COGS is displayed as negative with the 'amount type' set to either 'null' or to 'balance expected sign' . I assumed that a debit amount in an account 5 which has 'account type' = Expense and 'account sign' = natural would print just as a number without a negative sign.  I would then define a calculation of Margin = Revenue - COGS but I had to sum them to get the right number.  I would have expected to sum them if I was using 'accounted sign'.
When I set the amount type for COGS to 'Balance - accounted sign ' it still printed as negative even though it is a debit value.

**Comment by adaxa-steven** [comment]
please see attached testing results from https://test-feature.idempiere.org:3243/webui/
[carlos percent test.pdf](https://github.com/idempiere/idempiere/files/9775856/carlos.percent.test.pdf)

**Comment by nmicoud** [comment]
hi,
Sorry, I won't have time to write the documentation this week - hope to be able to do it next week (but i can't guarantee as i will be on holidays after)

**Comment by CarlosRuiz-globalqss** [comment]
> please see attached testing results from https://test-feature.idempiere.org:3243/webui/ [carlos percent test.pdf](https://github.com/idempiere/idempiere/files/9775856/carlos.percent.test.pdf)

Thanks @adaxa-steven for your test case, answering the questions from your PDF:

> ... why not ordered by Key? Is there an option somewhere?

That's the info window automatically created when there is no info window for the table associated, by default is always ordered by the first column discovered, in this case the Tenant column.

The option to make it work better is to create an info window for that table.

> I have the feeling the process should not change the actual number stored if it a % regardless of whar the multiplier and the rounding factor says ... it should just leave it as some number like 35.092713456789 and then there should be a ‘format pattern’ on the line that ‘overwrites’ whatever format pattern may be on the column definition

You did it right, the configuration of 0.001 and then 1000 for the multipliers does the trick in the right way.

The numbers are stored in the database without rounding (because you didn't define rounding), so in database they look as:
1234.06789
800.99999
433.06790
35.09271276801473215500000

The problem is that you cannot define different "Format Pattern" for the same column, that's not used directly from the financial report for anything, the Format Pattern is just copied into the print format item, and you cannot have different pattern for different lines in the print format.

A potential solution could be to define a third column and in the print format define that the value is printed just for certain line.

Look how I did it on top of your test case:

ExamplePercentInOtherColumn

**Comment by CarlosRuiz-globalqss** [comment]
Tested successfully by @nmicoud

**Pull request merged**
