### PR TITLE
IDEMPIERE-4855 Records of Tab level 2 disappear in particular case.

### PR DESCRIPTION
**Pull request by hengsin**
https://idempiere.atlassian.net/browse/IDEMPIERE-4855

### CODE REVIEW

**Review by CarlosRuiz-globalqss — APPROVED** [review]
tested - solved the issue reported

**Comment by HideakiHagiwara** [comment]
Thanks @hengsin for my pull request review and created new pull request.

I checked your pull request and tested some case.
Your pull request seems fine. 

So, I would like to confirm bad point of my pull request.
I would be happy if you could tell me.

I reviewed bad point of my pull request.

I think most bad point of my pull request is to activate All detail tab.
It's a waste of system resources and bad to performance.
I should activate active detail tab only.
Right?

I would be grateful if you could let me know if there are any other bad points or adverse effect as far as you can think of it.

I would like to get a better understanding of the window engine.
:-D

Best Regards,

**Comment by hengsin** [comment]
hi @HideakiHagiwara ,

Yes, that's the issue here. Where possible, we try to activate a detail tab when it is visible (for e.g when level 0 tab is header, level 2 tab is definitely invisible).

Regards,
Low

**Comment by HideakiHagiwara** [comment]
Hi, @hengsin 
Thanks quick response.
And thank you for your teaching.

I would like to keep learning Window Engine and other iDempiere system.
Please let me know if you have another chance.

In appreciation I'll show you around Japan, If you come again Japan.
I knew you came to HAKONE in Japan.
:-D

**Comment by hengsin** [comment]
thanks for the invitation (I've been to Japan twice - Hokkaido and Tokyo). As for now, I can't even travel to my parent's house that's just 30km away :(

**Pull request merged**
