### PR TITLE
IDEMPIERE-4871 Print Format Item Script Data Type Support (fix backward compatibility issue)

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
https://idempiere.atlassian.net/browse/IDEMPIERE-4871

### CODE REVIEW

**Comment by tony-tspc** [comment]
Hi Carlos as reported in Google Groups, everything is now working as expected. Just have an issue with what the following code highlighted in grey is trying to achieve. From what I can see the columnType will always be VARCHAR for the Script column itself, so the displayType wil be set to TEXT. Then further down the displyType is explicitly set to NUMBER.

script4

**Comment by tony-tspc** [comment]
In the original IDEMPIERE-4871 commit, I think the displayType should be have been set based on the value returned from the beanshell interpreter. This would enable displaying results other than just a number. I am working on a solution to implement this if you think it would be worthwile.

**Comment by tony-tspc** [comment]
Currently "NF8.2 Print Format Item Script" is not working in master, this pull request will at least allow that feature to work again as it does in 8.2 release. I will add my suggested changes to a feature request, if that is preferred.

**Comment by hengsin** [comment]
Hi @tony-tspc , I will merge this and please add your suggested changes as a separate feature request ticket.

**Review by hengsin — COMMENTED** [review]
tested by tony

**Comment by tony-tspc** [comment]
Thanks @hengsin

**Pull request merged**
