### PR TITLE
IDEMPIERE-5274 : Report customization panel : increase width of print…

### PR DESCRIPTION
**Pull request by nmicoud**
… format name

### CODE REVIEW

**Comment by nmicoud** [comment]
Hi,
The change forces the width to 400px (not sure if is the best way)

Regards,

Nicolas

**Comment by hengsin** [comment]
[IDEMPIERE-5274.patch.txt](https://github.com/idempiere/idempiere/files/8561329/IDEMPIERE-5274.patch.txt)

hi @nmicoud , instead of setting a fixed width for the name component, the attach patch works fine for me. please check it out.

**Comment by nmicoud** [comment]
hi @hengsin 
perfect! 
thanks

**Review by hengsin — APPROVED** [review]
tested

**Pull request merged**
