### PR TITLE
IDEMPIERE-5567 Support of UUID as Key (FHCA-4195)

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
https://idempiere.atlassian.net/browse/IDEMPIERE-5567

- Fix Record UUID editor

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [x] I have tested the direct scenario that my code is solving
- [ ] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by CarlosRuiz-globalqss** [comment]
Hi @hengsin / @PeterTakacs300 

The record UUID editor was working wrongly.

It can be tested in the _Test_ window, field _Record UUID_

The problem is that when a table is selected, for example M_Product, the editor was saving the M_Product_ID instead of the M_Product_UU

Regards,

Carlos Ruiz

**Comment by hengsin** [comment]
hi @CarlosRuiz-globalqss , sounds much simpler to me that we just use a different editor for RecordUID instead.

**Comment by CarlosRuiz-globalqss** [comment]
> hi @CarlosRuiz-globalqss , sounds much simpler to me that we just use a different editor for RecordUID instead.

I can work on that direction, but I think 98% of the code will be the same, so, I would think is harder to maintain having two almost identical sources.

Or I would need to do a RecordIDEditor and RecordUUIDEditor extend a new RecordEditor class, and at the end we'll have same if(s) there.

But, if that's your preference I can work on that direction.

**Comment by CarlosRuiz-globalqss** [comment]
> hi @CarlosRuiz-globalqss , sounds much simpler to me that we just use a different editor for RecordUID instead.

Hi @hengsin - implemented WRecordUUIDEditor separated from WRecordIDEditor using an abstract class WRecordEditor

Tested and is working fine.

**Comment by CarlosRuiz-globalqss** [comment]
Conflict solved in org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/info/InfoProductWindow.java

**Comment by hengsin** [comment]
[pr1837.patch.txt](https://github.com/idempiere/idempiere/files/11523595/pr1837.patch.txt)
- refactoring to remove all the if _UU checking.

**Comment by CarlosRuiz-globalqss** [comment]
Thanks  @hengsin - patch successfully tested and integrated

**Review by hengsin — APPROVED** [review]
tested

**Pull request merged**
