### PR TITLE
IDEMPIERE-2853: Fixing Tab Editor process do not shows

### PR DESCRIPTION
**Pull request by dpansheriya**

### CODE REVIEW

**Comment by dpansheriya** [comment]
This patch contain fix for regression issue due to dropping isSort field.

**Review by hengsin — CHANGES_REQUESTED** [review]
I believe we should add back the issorttab grid field (it can be hidden), this is potentially breaks lots of stuff out there.

**Comment by CarlosRuiz-globalqss** [comment]
Ah yes - this looks bad, I see references in core code about IsSortTab for example in:
GenericZoomProvider
lots of calls to GridTabVO.isSortTab() which has not been moved to the new approach.

What @hengsin suggest is better - restore the old field in a read-only mode and fill it properly via beforeSave.

I'm closing this one - in favour of the suggested approach.

**Comment by CarlosRuiz-globalqss** [comment]
replaced with https://github.com/idempiere/idempiere/pull/885

**Pull request closed without merging**
