### PR TITLE
IDEMPIERE-4479 - Allow define columnSql in AD_Field

### PR DESCRIPTION
**Pull request by igorpojzl**
Jira: https://idempiere.atlassian.net/browse/IDEMPIERE-4479

I dont know how to add properly change in AD_Field_v and AD_Field_vt.
 c.columnsql, -> COALESCE(f.columnsql, c.columnsql)::character varying(4000) AS columnsql,
 
 Views in Attachment:
[AD_Field_vt.txt](https://github.com/idempiere/idempiere/files/6591909/AD_Field_vt.txt)
[AD_Field_v.txt](https://github.com/idempiere/idempiere/files/6591910/AD_Field_v.txt)

### CODE REVIEW

**Comment by CarlosRuiz-globalqss** [comment]
Hi @igorpojzl - you can see for example how I did it here for a similar case:
https://github.com/idempiere/idempiere/commit/53d3328

**Comment by igorpojzl** [comment]
Thank you, commited changes.

**Comment by CarlosRuiz-globalqss** [comment]
Hi @igorpojzl - can you please move the migration script to the folder i8.2

**Review by CarlosRuiz-globalqss — CHANGES_REQUESTED** [review]
@igorpojzl - please also generate the model classes for AD_Field

And please delete the lines 219 to 225 in the class MField, this is the
`if (isDisplayed()) {`  block

**Comment by igorpojzl** [comment]
Commited.

**Comment by CarlosRuiz-globalqss** [comment]
Thanks @igorpojzl 
can you please move the migration script to the folder i8.2?

**Comment by igorpojzl** [comment]
Commited

**Review by CarlosRuiz-globalqss — APPROVED** [review]

**Pull request merged**
