### PR TITLE
IDEMPIERE-4445 Color Picker field type is not rendered in grid mode s…

### PR DESCRIPTION
**Pull request by hengsin**
…how hex value

- fix working with grid view

https://idempiere.atlassian.net/browse/IDEMPIERE-4445

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [x] I have tested the direct scenario that my code is solving
- [ ] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

### CODE REVIEW

**Comment by norbertbede** [comment]
**merge result.**
image

hello
@hengsin are you sure this is what the user want to see ? 
IMHO this implementation is too technical. 
Users don't  want to see hex code. If they want, then click into the field, the editor openng, then copy hex from editor.
wdyt ? norbert

**Comment by hengsin** [comment]
well, if you prefer, I can remove the hex code, doesn't really matter for me.

**Comment by norbertbede** [comment]
hi @hengsin . 

sounds good. i assume the next. 

- state row render - display only color
- state row editable - when the record selected the editor still display the color only, but also additional pen icon. 
- state editor opened - change color, as editor allow, probably if editor has copy option then enable it.

ps. if not complicated then on hover copy icon can be displayed - as you previously designed on copy values - but this is for now unrelevant, once we return back to copy then we make a common design for each fieldtypes. 

that is my suggestion.
norbert

**Comment by hengsin** [comment]
hi @PeterTakacs300  & @norbertbede , please test the new changes.

I've decided not to touch the existing editor style. If your want to change that as well, please create a new ticket for it. Would have to check with @nmicoud for the editor style changes as he is the initial user of the color field type.

**Comment by PeterTakacs300** [comment]
Hi @hengsin thank you, we tested it, looks good

**Pull request merged**
