### PR TITLE
IDEMPIERE-4878 : Thin scrollbars

### PR DESCRIPTION
**Pull request by nmicoud**
Co-Authored-By: pmargery <87129041+pmargery@users.noreply.github.com>

### CODE REVIEW

**Comment by nmicoud** [comment]
Hi,
Is a first commit for thin scrollbars.
There are still several ones which are still "big":
- horitontal on windows
- vertical on process
- vertical/horizontal on reports
- vertical on About (Credits) and horizontal on About (Info)

Any hint will be appreciated so we can fix them

Regards

Nicolas

**Comment by hengsin** [comment]
Hi @nmicoud ,

Can you post some before and after images to the tickets?

I'm not seeing any differences at my testing here, perhaps this is OS and Browser dependent.

**Comment by hengsin** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width - very poor compatibility across browser. While you can try to simulate that at Chrome/Safari with ::-webkit-scrollbar, it is not exactly the same thing. I would recommend not to add this to core until it is widely supported by most main stream browser (as it is, firefox has < 5% market share).

**Comment by nmicoud** [comment]
Not sure to understand what you recommend here ; stop working on that ticket and return "later" (when a single syntax will work for all browsers)?

**Comment by hengsin** [comment]
Hi @nmicoud , that's what I recommend. It is very verbose and difficult to maintain with current compatibility issue.

**Comment by nmicoud** [comment]
ok, thanks for confirming this

**Pull request closed without merging**
