### PR TITLE
IDEMPIERE-5567 Support of UUID as Key (FHCA-4195) - fix oracle migration script

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
https://idempiere.atlassian.net/browse/IDEMPIERE-5567?focusedCommentId=50544

Fix issue reported by @nmicoud - oracle treats empty string '' as null

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [ ] I have tested the direct scenario that my code is solving
- [ ] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by nmicoud** [comment]
I think is ok, but perhaps same fix should be applied to
ALTER TABLE t_selection_infowindow ADD t_selection_uu VARCHAR2(36 CHAR) DEFAULT '' NOT NULL;
(this table is empty on my test DB, so i didn't raise error, but just tried on production and it fails too).


(And I think you anticiped this issue as 202304171928_IDEMPIERE-5567.sql contains
ALTER TABLE t_selection_infowindow MODIFY t_selection_uu DEFAULT ' ';)

**Comment by CarlosRuiz-globalqss** [comment]
Thanks  @nmicoud - added the fix for that line too

**Review by nmicoud — APPROVED** [review]
No more error ! thanks

**Comment by CarlosRuiz-globalqss** [comment]
Tested by @nmicoud

**Pull request merged**
