### PR TITLE
IDEMPIERE-6047 - Fix report dialog showing the parameter cut in verti…

### PR DESCRIPTION
**Pull request by d-ruiz**
…cally on Chrome

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [ ] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [ ] I have checked my code and corrected any misspellings
- [ ] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [ ] I have tested the direct scenario that my code is solving
- [ ] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by CarlosRuiz-globalqss — CHANGES_REQUESTED** [review]
I'm deploying to test-feature for testing purposes

from some minor tests it seems the change makes it look better in chrome but not in firefox

**Comment by CarlosRuiz-globalqss** [comment]
@d-ruiz - please check my comment at:
https://idempiere.atlassian.net/browse/IDEMPIERE-6047?focusedCommentId=50567

I think it fixes the problem in chrome but now firefox doesn't look good when the mouse is there.

**Review by CarlosRuiz-globalqss — APPROVED** [review]
it looks OK

**Comment by CarlosRuiz-globalqss** [comment]
Hi @hengsin 
tested in https://test-feature.idempiere.org:3243/webui/index.zul?Action=Zoom&AD_Table_ID=445&Record_ID=100
it looks OK in chrome and firefox now.

Are you OK with the approach?

**Review by hengsin — APPROVED** [review]
looks good

**Pull request merged**
