### PR TITLE
IDEMPIERE-4368: Allow Define Default Saved Query for User

### PR DESCRIPTION
**Pull request by igorpojzl**
https://idempiere.atlassian.net/browse/IDEMPIERE-4368

### CODE REVIEW

**Comment by igorpojzl** [comment]
Sorry i forgot.
Commited migration scripts.

**Comment by d-ruiz** [comment]
Thanks Igor, the migration scripts are missing the script registration at the end ->

SELECT register_migration_script('yyyymmddhhmm_IDEMPIERE-####.sql') FROM dual
;

**Comment by igorpojzl** [comment]
Commited Missing registration scripts.

**Comment by d-ruiz** [comment]
Hi Igor, 

I added the finding of my tests to the JIRA ticket. Please check them.

Best Regards,
Diego Ruiz

**Comment by igorpojzl** [comment]
Commited Fix to load defaults only on initialization.

**Comment by d-ruiz** [comment]
Comments + Peer review patch added to the ticket.

**Comment by igorpojzl** [comment]
Hello @d-ruiz, commited review patch and moved migration scripts to 7.1 folder.

**Pull request merged**
