### PR TITLE
IDEMPIERE-5505 : Add Value and PrintName on GL_Category

### PR DESCRIPTION
**Pull request by nmicoud**
https://idempiere.atlassian.net/browse/IDEMPIERE-5505

# Pull Request Checklist

## Checklist:

- [X] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [X] My code follows the best practices of this project
- [X] I have performed a self-review of my own code
- [X] My code is easy to understand and review. 
- [ ] In hard-to-understand areas, I have commented my code.
- [X] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

### CODE REVIEW

**Comment by hengsin** [comment]
Some thing to fix/consider here - this break the existing convention that Value(Search Key) is mandatory.

**Comment by nmicoud** [comment]
you're right.

I see 2 options : 
 - add an update to set Value = GL_Category_ID and then set the column as Mandatory
 - change the name from "Value" to something else (my first idea was "Code", but Carlos suggested Value as it was the convention ; so maybe CategoryCode or something like that)

wdyt?

**Comment by CarlosRuiz-globalqss** [comment]
Yes, the Value column is usually mandatory and unique per tenant.

In principle I think you can set it to be equal as Name, that's the common setup in most sample tables.

**Comment by nmicoud** [comment]
Ok, I'll adapt the script and add an unique index on it.
I'll add it on the Migration Notes (as the script may fail because of that)

**Comment by nmicoud** [comment]
Added an update to populate Value before making the column mandatory.
And I don't think the migration note is needed as only the first 40 characters are used ; so it **should** not fail.
wdyt?

**Comment by nmicoud** [comment]
So a migration note should be enough ? 
I don't think we can found GL_Category.Name with lenght > 40
wdyt?
Another possibility would be to take 30 first characters of name and add the GL_Category_ID

**Comment by CarlosRuiz-globalqss** [comment]
I think is better to make the Value column same length as Name

A migration note sounds OK for me, it's still possible to get duplicates in the Name because there is no index to prevent that, but in real life that would be very unlikely.

**Comment by nmicoud** [comment]
Value length increased to 60
Just seen that there is an index "gl_category_name", so we can't find duplicate names.
I also realize I forgot to add a "gl_category_value" index, I'll do this asap

**Comment by nmicoud** [comment]
done !

**Comment by nmicoud** [comment]
hi @CarlosRuiz-globalqss ,
Done,
Thanks

**Review by CarlosRuiz-globalqss — APPROVED** [review]
tested

**Pull request merged**
