### PR TITLE
IDEMPIERE-4665 SearchQuery should behave the same as the toolbar butt…

### PR DESCRIPTION
**Pull request by d-ruiz**
…ons - role access,advanced button,dynamic display

https://idempiere.atlassian.net/browse/IDEMPIERE-4665

Test case scenarios:

**Advanced Button**
1. Log in as System
2. Navigate to the WIndow - SearchQuery record
3. Check the advanced Button flag

Expected Result
When logged in as SuperUser or GardenAdmin the select query Combobox should be displayed normally.
When logged in as GardenUser the Select Query Combobox should not be present on any window.

**Tab access restriction**
1. Log in as System
2. Create a new record in Role Toolbar Button Access with Action: Window, Window: Payment, Tab: Allocate, ToolbarButton: Window - SearchQuery

Expected Result
Log in as GardenAdmin. Open the Payment window

The Select Query should be displayed in the master tab. 
Navigate to allocate -> The select query combobox should be hidden for this tab.
Navigate back to Payment -> The select query should be visible again.

### CODE REVIEW

**Review by nmicoud — APPROVED** [review]
tested and it works as expected

**Comment by hengsin** [comment]
@d-ruiz , test case should be added to ticket instead of PR

**Comment by d-ruiz** [comment]
> @d-ruiz , test case should be added to ticket instead of PR

Yes @hengsin, my bad, I copied the test cases in the Jira ticket.

**Review by CarlosRuiz-globalqss — APPROVED** [review]
approving per feedback from @nmicoud

**Pull request merged**
