### PR TITLE
IDEMPIERE-4616 : Lead : add IsVendorLead

### PR DESCRIPTION
**Pull request by nmicoud**

### CODE REVIEW

**Review by CarlosRuiz-globalqss — CHANGES_REQUESTED** [review]
Please check comments in ticket [IDEMPIERE-4616](https://idempiere.atlassian.net/browse/IDEMPIERE-4616)

**Comment by nmicoud** [comment]
Hi Carlos,
Changes done

Thanks,

Nicolas

**Comment by CarlosRuiz-globalqss** [comment]
Hi @nmicoud, thanks for the change, I tested this successfully, it works perfect.

We just need the last step for integration, can you please create new feature page in wiki?

I think the suffix must be NF9.1

Regards,

Carlos Ruiz

**Comment by nmicoud** [comment]
Hi @CarlosRuiz-globalqss,

Page created : [https://wiki.idempiere.org/en/NF9.1_Vendor_Lead](https://wiki.idempiere.org/en/NF9.1_Vendor_Lead)
nb: the screenshot needs to be udpated - is taken from 6.2.

Regards,

Nicolas

**Review by CarlosRuiz-globalqss — APPROVED** [review]

**Pull request merged**
