### PR TITLE
IDEMPIERE-2853: Support for IADTabPanel as factory to add custom Tab …

### PR DESCRIPTION
**Pull request by dpansheriya**
…types

We developed this feature primarily for supporting DMS tab in DMS plugin, but this feature found quite useful on developing custom AD tab types.

### CODE REVIEW

**Comment by norbertbede** [comment]
Looks to be an important UX improvement.  We are testing the DMS plugin well so important to me, however, this generally usable for alternative tab implementations e.g tagging etc.

**Comment by CarlosRuiz-globalqss** [comment]
> Looks to be an important UX improvement. We are testing the DMS plugin well so important to me, however, this generally usable for alternative tab implementations e.g tagging etc.

I can help with test and peer review - how can we test this one?

**Comment by norbertbede** [comment]
> > Looks to be an important UX improvement. We are testing the DMS plugin well so important to me, however, this generally usable for alternative tab implementations e.g tagging etc.
> 
> I can help with test and peer review - how can we test this one?

Thanks @CarlosRuiz-globalqss  Deepak preparing a plugin for simple testing - without complex dms.  (something like calendar tab)

**Comment by dpansheriya** [comment]
@CarlosRuiz-globalqss I am working to make Calendar plugin compitable to master and send you.

**Comment by CarlosRuiz-globalqss** [comment]
Hi @dpansheriya - any news about this?

There are two conflicting files at this moment, and still pending for a test case.

**Comment by dpansheriya** [comment]
@CarlosRuiz-globalqss I shared test cases you on 21st December on personal chat.

**Pull request closed without merging**
