### PR TITLE
IDEMPIERE-4836: Adding Access tab for document status

### PR DESCRIPTION
**Pull request by dpansheriya**

### CODE REVIEW

**Review by hengsin — CHANGES_REQUESTED** [review]
this seems a good chance to add unit test case for mdocumentstatus (should be straightforward using the document status and role data in garden world).

**Comment by dpansheriya** [comment]
> this seems a good chance to add unit test case for mdocumentstatus (should be straightforward using the document status and role data in garden world).

Noted. Will update PR with unit test cases.

**Comment by CarlosRuiz-globalqss** [comment]
see my peer review comments in ticket

**Comment by dpansheriya** [comment]
I am closing this PR and creating new with latest branch.

**Pull request closed without merging**
