### PR TITLE
IDEMPIERE-5683 ModelForeignKeyTest throwing error when parallel tests

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [x] I have tested the direct scenario that my code is solving
- [x] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [x] New and existing unit tests pass locally with my changes
- [x] I have added unit tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by CarlosRuiz-globalqss** [comment]
Hi @hengsin 
ModelForeignKeyTest is throwing errors when ran using mvn in parallel

I tested from eclipse and is OK, also changed to non-parallel in mvn and is OK.

So, I tested moving the cache reset closer to where it needs to be tested and it seems to fix the problem.

Do that sound OK?

**Comment by hengsin** [comment]
hi @CarlosRuiz-globalqss , safer to also add the `@Isolated` annotation (https://junit.org/junit5/docs/5.7.1/api/org.junit.jupiter.api/org/junit/jupiter/api/parallel/Isolated.html)

**Comment by CarlosRuiz-globalqss** [comment]
Thanks @hengsin - the Isolated annotation worked fine.

**Review by hengsin — APPROVED** [review]
looks good

**Pull request merged**
