### PR TITLE
IDEMPIERE-5683 Fix broken test

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
https://idempiere.atlassian.net/browse/IDEMPIERE-5683

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [x] I have tested the direct scenario that my code is solving
- [x] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by CarlosRuiz-globalqss** [comment]
Hi @hengsin 

For the implementation of IDEMPIERE-5683 I added Fact_Acct as a dependent table to restrict deleting records when posting exists.

That validation was not there before and now the PaySelectFormTest is failing because of that.

I tend to think we must keep the validation, and fix the unit test, otherwise that means potentially that plugins could be leaving orphan records in Fact_Acct.

WDYT?

**Comment by CarlosRuiz-globalqss** [comment]
Ah, now that I'm fixing tests, I also added a fix for MTest class leaving records in the database after the tests (because they are created without trx)

**Comment by CarlosRuiz-globalqss** [comment]
> Ah, now that I'm fixing tests, I also added a fix for MTest class leaving records in the database after the tests (because they are created without trx)

Forget about this, I better open a new ticket because the test failed after I applied that fix

**Review by hengsin — APPROVED** [review]
looks good

**Pull request merged**
