### PR TITLE
IDEMPIERE-2826 Pull the promotions out of the trunk. Leave it as a plugin

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
https://idempiere.atlassian.net/browse/IDEMPIERE-2826

The promotions within core is intended to be replaced with the plugin here:
https://github.com/CarlosRuiz-globalqss/org.idempiere.promotion
to be integrated into -> https://github.com/victorsuarezis/org.idempiere.promotion

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [x] I have tested the direct scenario that my code is solving
- [x] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

### CODE REVIEW

**Comment by hengsin** [comment]
Well, I'm not against or in favour of this move but I think as a community project, there should be rules/guidelines for the removal of a core feature to external plug-in (this is not the same as web store or swing client which have been deprecated before the removal from core) .

**Comment by CarlosRuiz-globalqss** [comment]
> Well, I'm not against or in favour of this move but I think as a community project, there should be rules/guidelines for the removal of a core feature to external plug-in (this is not the same as web store or swing client which have been deprecated before the removal from core) .

Agree, opened a discussion at https://mattermost.idempiere.org/idempiere/pl/i1cqtm7pnj8czjomza11wz6imc

**Comment by CarlosRuiz-globalqss** [comment]
@hengsin - I have a doubt about my last commit:
https://github.com/idempiere/idempiere/pull/2395/commits/3642947aa000b74d3ad57b550a5f675b76fbb24f

I added in the migration script to inactivate the model validator and add a note in the help about using the plugin.

But, now thinking further, that can have unnoticed collateral effects, if the model validator is disabled, the server will start normally and the user won't notice that promotions are not being applied.

If we leave the record active and add just the note, the server will not start at all because the model validator class is not present anymore.

What do you think?  Better to leave it active to make the problem very notorious?

**Comment by hengsin** [comment]
Yes, better leave it as active.

**Comment by CarlosRuiz-globalqss** [comment]
> Yes, better leave it as active.

OK changed

**Comment by hengsin** [comment]
hi @CarlosRuiz-globalqss , if there's no response from https://github.com/victorsuarezis/org.idempiere.promotion, the plugin will be maintained at https://github.com/CarlosRuiz-globalqss/org.idempiere.promotion ?

Also, there's mention of improvements from logilite in the ticket, is that still applicable ?

**Comment by CarlosRuiz-globalqss** [comment]
> hi @CarlosRuiz-globalqss , if there's no response from https://github.com/victorsuarezis/org.idempiere.promotion, the plugin will be maintained at https://github.com/CarlosRuiz-globalqss/org.idempiere.promotion ?

Yes, I'm not using it but I can keep it updated until somebody that uses it can maintain it.

> Also, there's mention of improvements from logilite in the ticket, is that still applicable ?

No idea.

@dpansheriya  ?

**Comment by dpansheriya** [comment]
> > hi @CarlosRuiz-globalqss , if there's no response from https://github.com/victorsuarezis/org.idempiere.promotion, the plugin will be maintained at https://github.com/CarlosRuiz-globalqss/org.idempiere.promotion ?
> 
> Yes, I'm not using it but I can keep it updated until somebody that uses it can maintain it.
> 
> > Also, there's mention of improvements from logilite in the ticket, is that still applicable ?
> 
> No idea.
> 
> @dpansheriya ?

@CarlosRuiz-globalqss  recently we are not using promotion module much but in past done enhancement to it. So probably we can maintain it and may contribute those changes.

**Review by hengsin — APPROVED** [review]
looks good

**Pull request merged**
