### PR TITLE
IDEMPIERE-6005 Unit Test: Display the test method to be executed in t…

### PR DESCRIPTION
**Pull request by hengsin**
…he console

https://idempiere.atlassian.net/browse/IDEMPIERE-6005

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [x] I have tested the direct scenario that my code is solving
- [x] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [x] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

### CODE REVIEW

**Comment by CarlosRuiz-globalqss** [comment]
Hi @hengsin 

I was able to test this successfully, with this command:
```
mvn clean verify  -DmaterializeProduct=none  -DskipTests=false
```

All unit tests passed without problem.

But, the execution time is now double:

Before:
```
[INFO] Total time:  06:11 min
```

After:
```
[INFO] Total time:  12:03 min
```

Is that expected?

**Comment by hengsin** [comment]
not really, perhaps should revert the smalll refactoring change, will check.

**Comment by hengsin** [comment]
hi @CarlosRuiz-globalqss , found the error that causes the issue above. Also I've added a new assembleRepository flag that can be used to further reduce the time needed to run unit test (-DassembleRepository=none).

**Review by CarlosRuiz-globalqss — APPROVED** [review]
Thanks @hengsin 

I tested this successfully.

Two minor things:

* there are 79 messages `Running null` - what is that?  can be better described?

* the message
`Running testReverseReceiptAfterClosePO()`
maybe would be better
`Running MatchPOTest.testReverseReceiptAfterClosePO()`
or
`Running org.idempiere.test.base.MatchPOTest.testReverseReceiptAfterClosePO()`
?

**Comment by hengsin** [comment]
hi @CarlosRuiz-globalqss ,
- "Running null", that's a tycho 3.0.5 issue, fix after upgrade to 4.0.4 (it should print "Running org.idempiere.test.base.MatchPOTest" instead).
- Not sure that's possible, will check.

**Comment by CarlosRuiz-globalqss** [comment]
>     * "Running null", that's a tycho 3.0.5 issue, fix after upgrade tycho to 4.0.4 (it should print "Running org.idempiere.test.base.MatchPOTest" instead).

Ah, OK, not a big deal if is solved with https://github.com/idempiere/idempiere/pull/2201
I'm wondering when running in parallel, it won't get interlaced?  or the parallelism works is within every class?

**Comment by hengsin** [comment]
Added class name prefix and yes, it would get interlaced when test is being run in parallel.

**Comment by CarlosRuiz-globalqss** [comment]
Hi @hengsin 

I don't know if is related to this ticket - or something broke it, but unit tests are now failing in my laptop with these errors:
```
Results:

Failures:
  PaySelectFormTest.testPaySelect:216
  RequisitionTest.testComplete:84 Terminated ==> expected: <false> but was: <true>

Tests run: 386, Failures: 2, Errors: 0, Skipped: 0
```

**Comment by hengsin** [comment]
ok, will test again.

**Comment by hengsin** [comment]
hi @CarlosRuiz-globalqss , that's due to a bug introduce by IDEMPIERE-5949. I've push the fix for it and all unit test pass now.

**Pull request merged**
