### PR TITLE
IDEMPIERE-5732 Cache reset should happens after commit of transaction

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
https://idempiere.atlassian.net/browse/IDEMPIERE-5732

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [x] I have tested the direct scenario that my code is solving
- [ ] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by CarlosRuiz-globalqss** [comment]
Hi @hengsin - for your consideration I added the patch here with two changes:

1 - added removeTrxEventListener to the rollback too

2 - removed your code from TableElementHandler because it seems duplicate after applying this patch
However your code there removes the cache immediately instead of scheduling for later, so maybe there is a difference that you need, if that's the case, then we can leave the 2pack code there.

**Comment by hengsin** [comment]
[pr1850.patch.txt](https://github.com/idempiere/idempiere/files/11849157/pr1850.patch.txt)
- Remove synchronize for thread pool and trx event listener (for performance)
- Restore immediate cache reset for TableElementHandler (need immediate reset here)
- Fix unit test error

**Review by hengsin — CHANGES_REQUESTED** [review]
hi @CarlosRuiz-globalqss , please review attached patch, thanks.

**Comment by hengsin** [comment]
hi @CarlosRuiz-globalqss , please review the attached patch above when you have time, thanks.

**Comment by CarlosRuiz-globalqss** [comment]
Thanks @hengsin 

I tested your patch successfully.

I added a minor change at:
https://github.com/idempiere/idempiere/pull/1850/commits/d605f7042e068bfc4d94a9e4fec0ef59755b5b6d

If you are OK with that, I think this is ready for pushing.

**Review by hengsin — APPROVED** [review]
tested

**Pull request merged**
