### PR TITLE
IDEMPIERE-4344 : Add a ProcessFactory class to the org.idempiere.webs…

### PR DESCRIPTION
**Pull request by nmicoud**
…ervices package

### CODE REVIEW

**Comment by hengsin** [comment]
why is this necessary ?

**Comment by globalqss** [comment]
> why is this necessary ?

this is a prerequisite for https://github.com/idempiere/idempiere/pull/125
@nmicoud splitted the ticket in two pieces.

**Comment by nmicoud** [comment]
Hi,
1 : I was not sure about the name of the class, so I copy the org.idempiere.webservices\WEB-INF\src\org\compiere\model\WS_ModelFactory.java ; what name do you like ?
2 : ok, I'll update the PR

**Comment by hengsin** [comment]
Hi @nmicoud,

Anything that follows the common Java convention (see https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html#:~:text=Class%20names%20should%20be%20nouns,such%20as%20URL%20or%20HTML) will do. 

Regards,
Low

**Comment by nmicoud** [comment]
Hi @hengsin ,
PR updated

Thanks for your review/guidance

Nicolas

**Pull request merged**
