### PR TITLE
IDEMPIERE-3044 : Add IsHighVolume on Tab

### PR DESCRIPTION
**Pull request by nmicoud**
Hi,
Model classes have Release 10 (whereas I think it should be 9).
I think is because the branch is created against master branch.
If it needs to be changed, can you explain the steps or point me to a place in wiki (I didn't find it)
Thanks
Nicolas

### CODE REVIEW

**Comment by CarlosRuiz-globalqss** [comment]
> Hi, Model classes have Release 10 (whereas I think it should be 9). I think is because the branch is created against master branch. If it needs to be changed, can you explain the steps or point me to a place in wiki (I didn't find it) Thanks Nicolas

It doesn't matter now, model classes from R9 and R10 are now the same.

Regards,

Carlos Ruiz

**Review by CarlosRuiz-globalqss — APPROVED** [review]
Tested

**Comment by nmicoud** [comment]
I was not speaking about the 'structure', but just of those changes:
- *  @version Release 9
+ *  @version Release 10

I_AD_BroadcastMessage.java which was updated 3 days ago has @version Release 9
whereas I_AD_Tab (just updated) has @version Release 10

Shouldn't all those classes have the same release version number?

**Comment by CarlosRuiz-globalqss** [comment]
> Shouldn't all those classes have the same release version number?

Is just a comment, not a big deal.

**Pull request merged**
