### PR TITLE
IDEMPIERE-6193: Trial Balance : remove lines where account has no beg…

### PR DESCRIPTION
**Pull request by nmicoud**
…inning balance and movement

https://idempiere.atlassian.net/browse/IDEMPIERE-6193

# Pull Request Checklist

- [X] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [X] My code follows the best practices of this project
- [X] I have performed a self-review of my own code
- [X] My code is easy to understand and review. 
- [X] I have checked my code and corrected any misspellings
- [X] In hard-to-understand areas, I have commented my code.
- [X] My changes generate no new warnings
### Tests
- [X] I have tested the direct scenario that my code is solving
- [ ] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

### CODE REVIEW

**Comment by nmicoud** [comment]
Hi,
I've created a draft PR as I would like to be sure of the approach.
In the doIt part, you can easily change the value of withDel and see effects.

Also, I'm not sure about the name of the parameter.
The best I could find is IsDelLinesNoBalanceAndMovement -> Delete lines with no beginning balance and movement.

Thanks,

Nicolas

**Comment by norbertbede** [comment]
IncludeAllAccounts or isIncludeAllAccounts ?

**Comment by nmicoud** [comment]
Maybe too generic? but maybe with a good description, that can be enough

**Comment by CarlosRuiz-globalqss** [comment]
Hi @nmicoud,

Here is the patch suggested for the query:
[pr2422_PR0.patch.txt](https://github.com/user-attachments/files/17779106/pr2422_PR0.patch.txt)

I'm wondering if we need a parameter for this, for me it makes sense to have it by default, it doesn't add any value to have a line with zero open balance, and no movement.

I'm also wondering if opening balances with zero value are worthy to have there, even if they have movements (that's something that maybe we can ask Steven).

I would like also to have a parameter that doesn't generate opening lines at all, that would be more useful in some cases where you just want to report the movements.

So, my suggestion:
- do not add a new parameter for this, leave it as default as I think is not adding value to have historical zero accounts there
- we can ask Steven if is worthy to add lines that have movements with a zero beginning balance, if the beginning balance is zero then is unnecessary there, but I don't know if Steven has some usage for those beginning lines
- add a parameter to not add beginning balances at all - if that parameter is set then we simply don't call createBalanceLine method

WDYT?

Regards,

Carlos Ruiz

**Comment by nmicoud** [comment]
Hi @CarlosRuiz-globalqss 

Patch is good 

_>     * do not add a new parameter for this, leave it as default as I think is not adding value to have historical zero accounts there_

Agree to not have a parameter to remove those unnecessary lines. I wanted first to add a parameter to preserve backward compatibility, but indeed, it makes no sense to display them. And if someone complain, we can easily add a SysConfig key later.


_>     * we can ask Steven if is worthy to add lines that have movements with a zero beginning balance, if the beginning balance is zero then is unnecessary there, but I don't know if Steven has some usage for those beginning lines_

I would tend to think that having an opening balance with 0 make sense as it's obvious the beginning balance is 0.
Anyway Steven is the referent so we should wait for his opinion.


_>     * add a parameter to not add beginning balances at all - if that parameter is set then we simply don't call createBalanceLine method_

What would be the interest of having a report without opening lines here?
I mean, it's already there "Accounting Fact Details" :-/ Or reason is to be able to have all from a single menu entry?

Regards,

Nicolas

**Comment by CarlosRuiz-globalqss** [comment]
> Agree to not have a parameter to remove those unnecessary lines. I wanted first to add a parameter to preserve backward compatibility, but indeed, it makes no sense to display them. And if someone complain, we can easily add a SysConfig key later.

OK

> What would be the interest of having a report without opening lines here? I mean, it's already there "Accounting Fact Details" :-/ Or reason is to be able to have all from a single menu entry?

OK, you're right, I was just trying to make the report as it was before, but as you point it is unnecessary for this purpose.

**Comment by dpansheriya** [comment]
> 
> I'm also wondering if opening balances with zero value are worthy to have there, even if they have movements (that's something that maybe we can ask Steven).
> 
As per my experiance working with accountants here, they prefer to have opening balance with 0 when account has movement in given period. So it is good to keep it.

**Comment by CarlosRuiz-globalqss** [comment]
> As per my experiance working with accountants here, they prefer to have opening balance with 0 when account has movement in given period. So it is good to keep it.

Right @dpansheriya - the patch from Nicolas doesn't remove those opening lines when there is movement within the period, it just removes zero opening lines when there is no movement.

**Review by CarlosRuiz-globalqss — APPROVED** [review]
Hi @hengsin - I tested this one successfully - do you have any objection or a better idea how to implement it?

At first we thought this required a new parameter, but after testing I think is not needed as I think it doesn't add any value to show a zero being balance with no movements.

**Review by hengsin — APPROVED** [review]
looks good

**Pull request merged**
