### PR TITLE
IDEMPIERE-3561 : QuickEntry panel doesn't use ZoomCondition - wip

### PR DESCRIPTION
**Pull request by nmicoud**
Hi,
See comments in ticket

### CODE REVIEW

**Comment by hengsin** [comment]
hi @nmicoud , is this still being work on ?

**Comment by nmicoud** [comment]
hi,
I'm facing the issue described in the ticket and don't know how to handle it

**Comment by hengsin** [comment]
Hi @nmicoud , see my comments at the ticket. The current approach is wrong.

**Comment by nmicoud** [comment]
closing as it outdated

**Pull request closed without merging**
