### PR TITLE
IDEMPIERE-4286 : add MOrg.get method with transaction name

### PR DESCRIPTION
**Pull request by nmicoud**
So it can be used by AFTER_NEW event

### CODE REVIEW

**Comment by hengsin** [comment]
we should not cache PO with trx name

**Comment by nmicoud** [comment]
so what should I do in this particular case ?
replace :
MOrg.get(ctx, po.getAD_Org_ID(), trxName)
by a direct sql ?

**Comment by hengsin** [comment]
you can retrieve it using the normal PO method but you shouldn't put that directly into s_cache. The problem is after your trx/trxname ends, you now have a PO with an invalid trxName in the global cache. The next operation that get that PO from s_cache can cause havoc with it.

**Comment by nmicoud** [comment]
Your solution (new MOrg(ctx, po.getAD_Org_ID(), trxName)) is working, thanks for the tip.
Closing the branch

**Pull request closed without merging**
