### PR TITLE
IDEMPIERE-4965 Code reutilization for PO instantiation

### PR DESCRIPTION
**Pull request by saulojg**
https://idempiere.atlassian.net/browse/IDEMPIERE-4965

### CODE REVIEW

**Comment by hengsin** [comment]
hi @saulojg ,

This should be added to https://github.com/idempiere/idempiere/pull/877 for IDEMPIERE-4842 and change AnnotationBasedModelFactory to extend AbstractModelFactory

Regards,
Low

**Review by hengsin — CHANGES_REQUESTED** [review]
please merge the changes to https://github.com/idempiere/idempiere/pull/877 instead.

**Comment by saulojg** [comment]
> please merge the changes to #877 instead.

Done.

**Comment by hengsin** [comment]
changes added to #877

**Pull request closed without merging**
