### PR TITLE
IDEMPIERE-4482 Mobile Improvements - Font

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
Change font to improve the L&F

https://idempiere.atlassian.net/browse/IDEMPIERE-4482

### CODE REVIEW

**Comment by hengsin** [comment]
I think that can all be moved to default/theme.css.dsp, below font-size: 14px; (line 21)

**Comment by CarlosRuiz-globalqss** [comment]
> I think that can all be moved to default/theme.css.dsp, below font-size: 14px; (line 21)

Done

**Review by hengsin — CHANGES_REQUESTED** [review]
Hi @CarlosRuiz-globalqss , since the font-family setting is global, we should remove the other unless it is different.

**Comment by CarlosRuiz-globalqss** [comment]
> Hi @CarlosRuiz-globalqss , since the font-family setting at default/theme.css.dsp is global, we should remove the other unless it is different.

Done

**Pull request merged**
