### PR TITLE
IDEMPIERE-5198 Print Format Cache do not reload Print Format Items

### PR DESCRIPTION
**Pull request by CarlosRuiz-globalqss**
https://idempiere.atlassian.net/browse/IDEMPIERE-5198

### CODE REVIEW

**Comment by hengsin** [comment]
It would be better if this can override the reset(int id) method and clear the corresponding AD_PrintFormat_ID cache entries when the record is change.

**Review by igorpojzl — APPROVED** [review]
Tested with 2 roles. No MissMatch Report Rendered.

**Comment by CarlosRuiz-globalqss** [comment]
> It would be better if this can override the reset(int id) method and clear the corresponding AD_PrintFormat_ID cache entries when the record is change.

Hi @hengsin - I didn't understand the suggestion.  The change proposed here (and successfully tested by @igorpojzl) is simply to change the key for the print format, that will use a bit more memory I guess, but is safe as the cached data depends on the role, in general the cache keys must reflect the variables that can potentially make the cache record different, that has been in past a common error for example caching translated things without language in the key.

**Comment by hengsin** [comment]
Hi @CarlosRuiz-globalqss , if reset(int id) is not override, the update of any print format record will trigger the reset/clean up of the whole print format cache. It is not a must but it is less efficient without that.

**Comment by CarlosRuiz-globalqss** [comment]
> Hi @CarlosRuiz-globalqss , if reset(int id) is not override, the update of any print format record will trigger the reset/clean up of the whole print format cache. It is not a must but it is less efficient without that.

Understood, can you please provide a patch, I don't know how to do that, and didn't find any example of "reset(int id)" in code

Maybe the only one applicable is in MWorkflow line 191, but the implementation there seems to reset the whole cache when calling to reset one id.

**Comment by hengsin** [comment]
[1197_pr.patch.txt](https://github.com/idempiere/idempiere/files/8123451/1197_pr.patch.txt)

Hi @CarlosRuiz-globalqss, please check the attached patch is ok for you.

**Comment by CarlosRuiz-globalqss** [comment]
Ready @hengsin - tested and integrated your patch.

**Review by hengsin — APPROVED** [review]
tested by carlos and igor

**Pull request merged**
